### ISSUE TITLE
Don't show julia version selection for openPackageDirectory command if only one is installed

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#1]

**Comment by davidanthoff** [comment]
I actually think this should not show any version selector, instead it should just show the packages for the version of julia that is configured as ``julia.executablePath``.

**Comment by davidanthoff** [comment]
As part of this, we should also rewrite that typescript code using ``async`` and ``await``.

**Comment by ZacLN** [comment]
This still doesn't work for me, my `JULIA_HOME` needs to point at `..../julia/usr/bin` for some reason

**Comment by davidanthoff** [comment]
Ok, moving this to 0.5.0, given that this doesn't work on your system. I'll fix this today.

**Comment by ZacLN** [comment]
#83
