### ISSUE TITLE
[feature] Adding Intellisense

### ISSUE THREAD

**Issue by aedrax** [JuliaEditorSupport/julia-vscode#10]
Adding Intellisense to functions and variables that have type definitions

**Comment by novatena** [comment]
In a new pull request, I implemented a very basic intellisense based on REPLCompletions and CodeTools. I am followinng the vscodepythong extension. The code is still horrible, because I am very new to typescript and javascript :)

**Comment by davidanthoff** [comment]
Also closing this, we have some support for this on master now.
