### ISSUE TITLE
'print(\mu)' don't change to 'print(μ)' while pressing the tab key

### ISSUE THREAD

**Issue by sunqi1993** [JuliaEditorSupport/julia-vscode#103]
![image](https://cloud.githubusercontent.com/assets/12682690/20625071/c541c5f6-b34b-11e6-8903-9316374549b1.png)

**Comment by bthlgd** [comment]
I think this is a bug of vscode snippet.
You can try to add a space before \mu, then it works as expected.

**Comment by davidanthoff** [comment]
I think one option would be to move these latex completions into the language server. I think @ZacLN had suggested that at some point? I'm not sure that would fix this, but it might be worth a try.

We could also get rid of [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/snippets/generate_latex_snippets.jl) script then, and it would be less work to keep the julia base list of latex completions in sync with this extension.

**Comment by ZacLN** [comment]
I'm going to do this this weekend. It just needs a function on the server file to locate words including the escape character then to provide a TextEdit rather than a simple word so that the initial backslash is removed
