### ISSUE TITLE
only send one line, instead of an expression

### ISSUE THREAD

**Issue by jin2fantasy** [JuliaEditorSupport/julia-vscode#108]
For example, if I press ctrl-Enter at first line of this expression:
```julia
for i in 1:10
    print(i)
end
```
Only `for i in 1:10` part is sent to terminal.
It's working though I have to keep pressing ctrl-Enter to evaluate whole expression.
But, below is not working.
```julia
string(1,
2,
3)
```
When I press ctrl-Enter at first line, only `string(1,` is sent to terminal and `)` is automatically appended, which is not my intention.
It would be good if whole expression is sent to terminal as Juno.

I'm on version 0.5.0-beta4.

**Comment by bthlgd** [comment]
as I know, this feature hasn't been implemented yet.

**Comment by davidanthoff** [comment]
I think the strategy for implementing this should be this: we send our own, custom request to our own language server from the extension. This request asks for block information, and then the extension executes the correct block.

The ``LanguageClient`` class has a ``sendRequest`` method, so I think on the extension side we should be able to send a message to the LS that is not part of the official protocol. On the LS side we can obviously just handle that message and return the required information.

I think the request just needs to have the cursor location as a parameter. The response should have the range information that should be executed, plus maybe a position where the cursor should be moved next (e.g. at the end of the next block).

In the future we could enhance this, e.g. optionally detect cells a la R Studio or something like that, but I think for starters this would be good enough.

**Comment by swt30** [comment]
I see the described behaviour (parenthesis being added to the end of an unfinished line when doing ctrl-enter) on 0.8.0-rc5, both osx and linux.

**Comment by davidanthoff** [comment]
@swt30 Hm, very strange, I can't reproduce that... Are you sure that you are running RC5 and haven't changed any default keyboard bindings? What you describe sounds to me like the execute block command... Sometimes you have to manually delete the folder for the julia extension in ``.vscode/extensions/`` before you install a new VSIX, could you maybe do that and then reinstall, just to be sure?

**Comment by swt30** [comment]
I figured it out - it's due to OhMyREPL.jl. OhMyREPL autocompletes the ending parenthesis when you type the opening one, and it triggers even when pasting into the REPL - see https://github.com/KristofferC/OhMyREPL.jl/issues/17. So not a VS Code issue.

**Comment by davidanthoff** [comment]
Great, thanks for digging in!
