### ISSUE TITLE
[Feature request] Option to disable linter

### ISSUE THREAD

**Issue by Allardvm** [JuliaEditorSupport/julia-vscode#112]
As you might be aware, the Julia linter still has an issue with relative module paths. I love the functionality that the linter provides, but due to this issue it's giving me so many false-positives that I'd like to have a way to disable it. Would it be possible to add a configuration option for this? I gave it a shot myself, but there are so many ways that this can be done (considering how you're interfacing with Julia from VS Code) that it's probably best if you tackle this yourself—most notably because you'll be able to consider how future functionality might hook into the same configuration system.

Thanks for the great package!

**Comment by ZacLN** [comment]
Ah yes this is a bit of a pain. I'll see if I can add a configuration option

**Comment by Allardvm** [comment]
Thanks for adding!

**Comment by ZacLN** [comment]
No problem!

**Comment by affans** [comment]
Has this been implemented? I too am having a lot of problems with the linter.

**Comment by davidanthoff** [comment]
The whole linter story will be much better in the next version of the extension, which is currently in alpha. We have some alpha builds on the release section here on github if you want to try it. But be warned, it is julia 0.6 only and an alpha, so probably has some other issues. But any feedback would be most welcome!
