### ISSUE TITLE
ellipsis isn't highlighted properly

### ISSUE THREAD

**Issue by ZacLN** [JuliaEditorSupport/julia-vscode#117]
At the moment only the first period is highlighted
@be5invis, maybe you could add this to the operator list?

**Comment by be5invis** [comment]
Sample code?

**Comment by ZacLN** [comment]
Sorry, I don't quite understand the tmLanguage spec. What I mean is that when you use three dots for splatting
``` f(x...)```
only the first of these is highlighted and the remaining two display as normal text which is slightly wonky.

Does this make sense?

**Comment by be5invis** [comment]
@ZacLN I've raised the priority of operators and added `...` into it. See #118

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/21259684/794e99a8-c3bd-11e6-9ab7-564f391a2e56.png)

**Comment by ZacLN** [comment]
Cheers! I'll check it on mine and merge
