### ISSUE TITLE
[feature] Go to Definition

### ISSUE THREAD

**Issue by aedrax** [JuliaEditorSupport/julia-vscode#12]
Either by right clicking and/or ctrl + clicking names of variables/functions/types

**Comment by davidanthoff** [comment]
Thanks @aedrax for these! I don't have the time to implement any of these features anytime soon, but they are obviously good suggestions, so maybe someone else will pick them up.

**Comment by aedrax** [comment]
Absolutely! I was thinking about trying my hand at these this weekend, but I've never done any extension development in Visual Studio Code before so we'll see how this goes!

**Comment by davidanthoff** [comment]
Make sure you take a look at the [Language Extension Guidelines](https://code.visualstudio.com/docs/extensions/language-support). The big question is whether we should implement a language server that speaks the [language server protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md), or whether this should be implemented directly in the extension.

The benefit of the language server would be that it could be written in julia, and there was at some point some interest from the juno crowd to also utilize that, i.e. one could even imagine a situation where there is one julia language server implementation that is used by both the Atom and the VS Code plugin. Also, you could probably use [JuliaParser.jl](https://github.com/JuliaLang/JuliaParser.jl) in that case, which might make things easier.

**Comment by davidanthoff** [comment]
This is now there on master, still a bit buggy, but I'm closing this issue for now.

**Comment by kindlychung** [comment]
Any plans for pushing this further? Thanks!

**Comment by davidanthoff** [comment]
I think this has been working for many releases?

**Comment by kindlychung** [comment]
Ah, sorry. Looks like I need to wait for a while after loading a project before I can get the ctrl-click feature working.

**Comment by davidanthoff** [comment]
Yes, our startup time story is not great right now. We know how to fix it, but it is a bit more involved.
