### ISSUE TITLE
Installation: julia.executablePath cannot have spaces on Windows

### ISSUE THREAD

**Issue by EricForgy** [JuliaEditorSupport/julia-vscode#128]
HI,

This is looking great! I just tried installing it and hit a snag because VS Code could not find my `julia.executablePath`. It turned out the reason is I installed Julia in: `C:\Program Files (x86)` and VS Code was not recognizing the space in the path. To fix it, I had to set the path to `C:\\PROGRA~2`. 

Documentation could use a minor update. 

Best regards,
Eric

**Comment by davidanthoff** [comment]
Thanks for reporting, this really is a bug and we should just be able to deal with those paths. I'll try to do a bug fix release soon.

**Comment by davidanthoff** [comment]
This is fixed in v0.5.1, which I just published to the marketplace.
