### ISSUE TITLE
Ctrl + Enter conflicts with editor.action.insertLineAfter

### ISSUE THREAD

**Issue by jhasse** [JuliaEditorSupport/julia-vscode#129]
VS Code has this keyboard shortcut on Linux and Windows:

```json
{ "key": "ctrl+enter",            "command": "editor.action.insertLineAfter",
                                     "when": "editorTextFocus && !editorReadonly" },
```

The Julia extension overrides it with `language-julia.executeJuliaCodeInREPL` which is quite annoying for people who use the normal behavior very often when editing code.

**Comment by davidanthoff** [comment]
Yes, this is a bit annoying, but ``ctrl+enter`` is soo common in the scientific community for executing code (e.g. Jupyter, Juno, RStudio) that I want to keep this as the default for now.

Having said that, I did just open a PR that limits this keybinding to julia files, so at least for any other file type ``ctrl+enter`` should give you the default VS Code behavior again.

Also, keep in mind that you can always override the keybindings as described [here](https://code.visualstudio.com/docs/customization/keybindings) if you don't like the default.

If anyone has a better idea how we might deal with this, please let us know.

**Comment by jhasse** [comment]
> Yes, this is a bit annoying, but ctrl+enter is soo common in the scientific community for executing code (e.g. Jupyter, Juno, RStudio) that I want to keep this as the default for now.

Would `ctrl+shift+enter` work?

> Also, keep in mind that you can always override the keybindings as described here if you don't like the default.

Thanks :) I've tried overriding it, but it didn't work somehow. I'll look into that again.

**Comment by davidanthoff** [comment]
@jhasse v0.5.1 is now published and should at least scope this to ``.jl`` files.

**Comment by jhasse** [comment]
thx :)

**Comment by davidanthoff** [comment]
I'm closing this for now. We might revisit these shortcuts, but not anytime soon.
