### ISSUE TITLE
Question: How to create a keyboard shortcut to open Julia terminal

### ISSUE THREAD

**Issue by EricForgy** [JuliaEditorSupport/julia-vscode#133]
Hi,

I see that I can create keyboard shortcuts in keybindings.json, but what is the `command` to open the Julia terminal? Thanks!

**Comment by davidanthoff** [comment]
It is ``language-julia.startREPL``. You can see all the command names in [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/package.json) file.
