### ISSUE TITLE
Linting Problems: The julia Language Server server crashed...

### ISSUE THREAD

**Issue by meowklaski** [JuliaEditorSupport/julia-vscode#138]
OS: Windows 10
VS Code: 1.8.1
Julia VS Code Extension: 0.5.1

Linting does not seem to be working correctly. 

VS Code consistently issues the message:

```
The julia Language Server server crashed 5 times in the last 3 minutes. 
The server will not be restarted. 
```

**Comment by ZacLN** [comment]
I'm afraid the linter seems to error out on a fair few files at the moment. For reference could you tell me (if possible):
- Are you on julia 0.5 or 0.6?
- Does the Lint.jl successfully lint the file when run from the REPL? (if so maybe add an issue upstream)
 
The next release should allow you to disable the linter until we find an alternative approach.

**Comment by meowklaski** [comment]
I am running Julia 0.5. 

It does seem to be an issue with Lint.jl - it is hanging on the following:

```julia
y = x +1
0 = 1
 = 1 = 1+ x
```

I definitely agree with disabling the linter. This is my first foray into Julia, and this just added to the bumps in the road of using a new (and very young) language.

**Comment by ZacLN** [comment]
If you're willing to fiddle a bit to get it setup, (and take into consideration the usual caveats to do with it being under development) you could try checking out the master branch (and then disable the linter in the Julia section of the vscode settings)

**Comment by meowklaski** [comment]
I may do that. Fortunately, it kind of takes care of itself since the language server crashes :P

**Comment by ZacLN** [comment]
Have you tried the [atom](junolab.org) plugin? That's much more complete than this and will give you a better experience at the moment!

**Comment by meowklaski** [comment]
I'll give it a shot! I like VS Code better overall, but I'll definitely try Atom for julia. Thank you :)

**Comment by davidanthoff** [comment]
I'll close this, ok? Just for reference, @meowklaski reported this as tonyhffong/Lint.jl#170.

**Comment by joseph-pollacco** [comment]
Same problem with Julia version 0.6 with VSC. It worked in the pass by now for unknown reasons stopped working.
