### ISSUE TITLE
Autocomplete is not working on Windows 10

### ISSUE THREAD

**Issue by rafaelmartinelli** [JuliaEditorSupport/julia-vscode#139]
Autocomplete keeps "Loading..." indefinitely on Windows 10 with Julia 0.5.0:
![julia02](https://cloud.githubusercontent.com/assets/10237929/22092922/8ee083ea-dde8-11e6-8d07-abf6c0382956.png)

I set julia.executablePath to julia.exe:
![julia03](https://cloud.githubusercontent.com/assets/10237929/22092964/d77f0fcc-dde8-11e6-9ec3-dddec6270b5a.png)
(I also tried with \\\\ instead of /)

I know VSCode finds the executable because as soon as I open the program, it launches julia.exe, which keeps one core busy all the time:
![julia01](https://cloud.githubusercontent.com/assets/10237929/22092991/0d1d9e5a-dde9-11e6-9fc1-52978006c74c.png)

Is it a bug? Any suggestions?

**Comment by ZacLN** [comment]
Hmm, something is failing immediately.

If you debug the extension you should get more information: 
- open `julia-vscode` located somewhere like `'~/.vscode/extensions/julia-vscode'` in vscode.
- hit F5 (hopefully) opening a new window.
- open a .jl file
- toggle output (`View: Toggle Output`) and switch to `julia Language Server` on the rhs.

Report back what it says!
If debugging doesn't work let me know and I'll give you an alternative metho

**Comment by rafaelmartinelli** [comment]
I tried to do what you said. At first, the folder name was "julialang.language-julia-0.5.1":
![julia01](https://cloud.githubusercontent.com/assets/10237929/22108474/831f3d6a-de3a-11e6-9b2b-50d11464c572.png)

I opened this folder in VSCode and hit F5. It then asked me this:
![julia02](https://cloud.githubusercontent.com/assets/10237929/22108491/9533d39e-de3a-11e6-9609-9cebea646738.png)

If I choose VSCode Extension Development, it asks me to configure Task Runner:
![image](https://cloud.githubusercontent.com/assets/10237929/22108556/d4d2d9be-de3a-11e6-99d6-b45eaeb6e1e0.png)

I tried npm and Typescript, but neither worked. It says it couldn't find npm.
Besides, I also tried Node.js as environment, but it says it couldn't find node.

**Comment by ZacLN** [comment]
Ok in the  "julialang.language-julia-0.5.1/scripts/languageserver/main.jl" comment out [lines 19-23](https://github.com/JuliaEditorSupport/julia-vscode/blob/v0.5.1/scripts/languageserver/main.jl#L19:L23) and on line 24 add 
```
const global ls_debug_mode = true
```
Then restart and bring up the console as above!

**Comment by rafaelmartinelli** [comment]
After doing the changes, it prints the following in "output":
`INFO: RECEIVED: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":9700,"rootPath":"c:\\Users\\<my-user>\\.vscode\\extensions\\julialang.language-julia-0.5.1","capabilities":{},"trace":"off"}}`
`INFO: `
`INFO: SENT: {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"definitionProvider":true,"signatureHelpProvider":{"triggerCharacters":["("]},"documentSymbolProvider":true}}}`
`INFO: `

But it still complains:
![image](https://cloud.githubusercontent.com/assets/10237929/22114497/dc5336e6-de50-11e6-9c8c-847e74587a86.png)

I then opened my project folder and opened the toy .jl file. After a while, it showed the completion:
![image](https://cloud.githubusercontent.com/assets/10237929/22115053/adbb5e9c-de52-11e6-80e8-cce0a7d99156.png)

However, if I open a more complicated code, it stalls:
![image](https://cloud.githubusercontent.com/assets/10237929/22115100/ed1ffb24-de52-11e6-9e1a-11133a5818ae.png)

The complete Julia Language Server Output is: 
[julia.txt](https://github.com/JuliaEditorSupport/julia-vscode/files/717168/julia.txt)

**Comment by davidanthoff** [comment]
How long have you waited? There is a significant pre-compile delay we have right now, and it might just be that what you are seeing is the delay from that.

The long version is this: right now the Linter will ``eval`` all the ``using`` statements in your code. Our extension has its own pre-compile cache, so the first time you type in something like ``using JuMP`` the process that handles all of these code integrations will be blocked until all of ``JuMP`` and its dependencies are precompiled. That can easily be longer than a minute. Once this first precompile is done, this delay should be gone, until you update your package directory. Could you try to just wait for a couple minutes and see whether things then start to work?

We do have a plan to solve this by moving the linter into yet another process that a) runs async and b) reuses the precompiled binaries of your normal julia installation. I'm pretty positive that these delays should be gone at this point. I'm still hopeful that I can finish that for the next version of the extension.

**Comment by jonathanBieler** [comment]
Sometimes it seems to get stuck, it usually stops to work when I'm working for a while, and looking at the processes I have a Julia process taking a full core, for hours that is. That said it depend on the file I have open.

**Comment by ZacLN** [comment]
I think this is down to repeated efforts to parse a file with specific syntax errors causing it to get stuck in a loop. I _may_ have a temporary (until we get new parser) fix for this on my next PR to master.

Does it seem to happen when editing files that define a module?

**Comment by rafaelmartinelli** [comment]
I waited more than 5 minutes and nothing happened. I think I'll wait for the next version of the extension. Right now I'm going out on vacation. I will try it again on February. Thank you all.

**Comment by rafaelmartinelli** [comment]
Sorry, I closed the issue unintentionally. It's opened again.

**Comment by davidanthoff** [comment]
Is there any chance that you could share the code that causes this? If you can't share it publicly, it would already help if you could share it just with @ZacLN and me for diagnostics.

**Comment by rafaelmartinelli** [comment]
Since I was not able to attach a zip file here, [I put the code in a Gist](https://gist.github.com/rafaelmartinelli/5e41ca87b585ca2529c11e6416863688).

It is the single commodity flow formulation for the TSP from [this book](https://www.amazon.com/Network-Flows-Theory-Algorithms-Applications/dp/013617549X). It works with any instance from [TSPLib](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp/).

**Comment by jonathanBieler** [comment]
I pinned down the line causing problem in my file:

    F(x,y,z) ~ max(x,y)cos(z)

So it seems there's a bug when dealing with `~`.

**Comment by davidanthoff** [comment]
I assume this is fixed with the new LS implementation, but we should double check and then close this issue.

**Comment by ZacLN** [comment]
Yep this is all sorted

**Comment by davidanthoff** [comment]
Alright, then I'm closing this, if someone still sees this on v0.6.0 beta, please reopen!
