### ISSUE TITLE
Extra "@" at beginning of autocompletion of macro call

### ISSUE THREAD

**Issue by novatena2015** [JuliaEditorSupport/julia-vscode#140]
To reproduce: type `@sh` and then Tab or Return to select the completion. The initial "@" is kept.

**Comment by davidanthoff** [comment]
I can reproduce this.

**Comment by ZacLN** [comment]
this is fixed on  the [cachie](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/30) PR which should be ready to go soon

**Comment by davidanthoff** [comment]
I'm closing this, assuming that this is fixed in v0.6.0, which we will probably release next week (beta out today, fingers crossed).
