### ISSUE TITLE
Relative paths for julia.executablePath

### ISSUE THREAD

**Issue by tshort** [JuliaEditorSupport/julia-vscode#142]
Using a relative path for `julia.executablePath` seems to work for the Julia terminal (`startREPL`), but it doesn't work for the language server.

I'm trying to cobble together a portable version of Julia with VSCode. [vscode-portable](https://github.com/garethflowers/vscode-portable) seems to work well. Now, the main issue is getting julia-vscode to start a version of Julia in an adjacent directory. I can set the package directory with the `JULIA_PKGDIR` environment variable set from portable-vscode. One easy option for this use case is to have an environment variable that points to the location of Julia.

**Comment by tshort** [comment]
For my use case, I found a decent work-around. I set `julia.executablePath` to `julia.exe`. Then, I adjusted the `PATH` environment variable to include the `bin` directory of Julia. 

For vscode-portable, I added the following two lines just after [this line](https://github.com/garethflowers/vscode-portable/blob/master/VSCodePortable/App/AppInfo/Launcher/VSCodePortable.ini#L11). With this organization, `Julia-0.5.0`, `julia-packages`, and `VSCode` are all in the same directory (`PortableApps` in my case).

```
JULIA_PKGDIR=%PAL:PortableAppsDir%\julia-packages
PATH=%PAL:PortableAppsDir%\julia-0.5.0\bin;%PATH%
```

This works well enough for me, so we can close this issue.

**Comment by davidanthoff** [comment]
Ok, great. We don't really control the startup of the language server, that happens somewhere in the implementation of the ``LanguageClient`` that we use. We just tell the language client to [start the language server](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/src/extension.ts#L204). I guess one could do a PR for the language client code that works with relative paths, but if you found a different workaround, I'll just close this for now.
