### ISSUE TITLE
Try to automatically find julia if julia.executablePath is null

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#143]
This should make things much easier for new users. Essentially on Windows we should just search in the default install locations, and on Mac we would look in ``/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia`` (or the correct version).

**Comment by waldyrious** [comment]
As an additional data point, I have julia installed via [Homebrew Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/julia.rb), which automatically symlinks `/usr/local/bin/julia` (i.e. I can simply type `julia` in the terminal and it works), but the VSCode configuration being `null` still prevented the extension from locating the executable.

**Comment by waldyrious** [comment]
@ZacLN just to be sure, was this fixed? I can't test my use case (described above) at the moment, but I went through recent commits in the repo looking for changes possibly related to this issue, and didn't manage to find anything.

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/commit/0b06bb07d3f9b4e1f98bd23b0655f456169937c4 updates the existing code for julia 1.0, let us know if this isn't working

**Comment by waldyrious** [comment]
Ah, right -- just tested `brew cask install julia`, and the result is indeed:

    $ ls -l $(which julia)
    lrwxr-xr-x  1 waldyrious  admin  62 Oct 10 11:54 /usr/local/bin/julia -> /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia

Thanks for the clarification.
