### ISSUE TITLE
vscode 1.9.0 terminal not working with Julia

### ISSUE THREAD

**Issue by ZacLN** [JuliaEditorSupport/julia-vscode#144]
Having updated to the latest VScode the terminal no longer seems to work with Julia (on Linux at least).

Sending text to the terminal  is followed by the REPL entering reverse search mode. Hitting TAB several times to access autocomplete also enters reverse search mode.

**Comment by davidanthoff** [comment]
On Windows things seem to work, at least the things I just tried. Can you maybe let me know a precise repo case and I'll try that?

**Comment by ZacLN** [comment]
1 - Enter VScode, open empty file, set to Julia and pull up terminal/Julia
2 - Make selection and send (this evaluates the code then pulls up reverse search)
3 - Exit reverse by  search by hitting Esc twice.
4 - Repeat 2

Also, hitting autocomplete (TAB) in the REPL when on a dot pulls up reverse search

[gif](https://giphy.com/gifs/26xBwTnmeySiCAEog)

**Comment by ZacLN** [comment]
I've partially fixed this by launching Julia with `rlwrap julia` in VScode and opened an issue upstream

**Comment by davidanthoff** [comment]
Thanks, yeah, this looks like a problem in vscode to me, I can't repo this on Windows. This microsoft/vscode#19815 is tracking the upstream issue.

**Comment by davidanthoff** [comment]
@ZacLN Is this fixed with VS Code 1.9.1?

**Comment by ZacLN** [comment]
The temporary fix suggested in the upstream issue is set as default. We may want to mention it in the docs
