### ISSUE TITLE
Cannot start language server on WIndows 7

### ISSUE THREAD

**Issue by xanadupark** [JuliaEditorSupport/julia-vscode#145]
Hello, 

I do not know this is just my case or unknown error, but I got the message:
`The julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

Julia version is:
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

and on Windows 7 32 bit
VScode version : 1.9.1
Julia extension version: 0.5.1

And the output of vscode:

ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Union{Int32,String}
This may have arisen from a call to the constructor Union{Int32,String}(...),
since type constructors fall back to convert methods.
 in convert(::Type{Nullable{Union{Int32,String}}}, ::Nullable{Int64}) at .\nullable.jl:17
 in JSONRPC.Request{Val{:initialize},Dict{String,Any}}(::Nullable{Int64}, ::Dict{String,Any}) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:9
 in parse(::Type{JSONRPC.Request}, ::String) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:37
 in run(::LanguageServer) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\languageserver.jl:28
 in include_from_node1 at .\loading.jl:488
 in process_options at .\client.jl:262
 in _start at .\client.jl:318
while loading C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\main.jl, in expression starting on line 41
[Info  - 오후 11:37:19] Connection to server got closed. Server will restart.
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Union{Int32,String}
This may have arisen from a call to the constructor Union{Int32,String}(...),
since type constructors fall back to convert methods.
 in convert(::Type{Nullable{Union{Int32,String}}}, ::Nullable{Int64}) at .\nullable.jl:17
 in JSONRPC.Request{Val{:initialize},Dict{String,Any}}(::Nullable{Int64}, ::Dict{String,Any}) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:9
 in parse(::Type{JSONRPC.Request}, ::String) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:37
 in run(::LanguageServer) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\languageserver.jl:28
 in include_from_node1 at .\loading.jl:488
 in process_options at .\client.jl:262
 in _start at .\client.jl:318
while loading C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\main.jl, in expression starting on line 41
[Info  - 오후 11:37:22] Connection to server got closed. Server will restart.
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Union{Int32,String}
This may have arisen from a call to the constructor Union{Int32,String}(...),
since type constructors fall back to convert methods.
 in convert(::Type{Nullable{Union{Int32,String}}}, ::Nullable{Int64}) at .\nullable.jl:17
 in JSONRPC.Request{Val{:initialize},Dict{String,Any}}(::Nullable{Int64}, ::Dict{String,Any}) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:9
 in parse(::Type{JSONRPC.Request}, ::String) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:37
 in run(::LanguageServer) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\languageserver.jl:28
 in include_from_node1 at .\loading.jl:488
 in process_options at .\client.jl:262
 in _start at .\client.jl:318
while loading C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\main.jl, in expression starting on line 41
[Info  - 오후 11:37:25] Connection to server got closed. Server will restart.
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Union{Int32,String}
This may have arisen from a call to the constructor Union{Int32,String}(...),
since type constructors fall back to convert methods.
 in convert(::Type{Nullable{Union{Int32,String}}}, ::Nullable{Int64}) at .\nullable.jl:17
 in JSONRPC.Request{Val{:initialize},Dict{String,Any}}(::Nullable{Int64}, ::Dict{String,Any}) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:9
 in parse(::Type{JSONRPC.Request}, ::String) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:37
 in run(::LanguageServer) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\languageserver.jl:28
 in include_from_node1 at .\loading.jl:488
 in process_options at .\client.jl:262
 in _start at .\client.jl:318
while loading C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\main.jl, in expression starting on line 41
[Info  - 오후 11:37:28] Connection to server got closed. Server will restart.
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Union{Int32,String}
This may have arisen from a call to the constructor Union{Int32,String}(...),
since type constructors fall back to convert methods.
 in convert(::Type{Nullable{Union{Int32,String}}}, ::Nullable{Int64}) at .\nullable.jl:17
 in JSONRPC.Request{Val{:initialize},Dict{String,Any}}(::Nullable{Int64}, ::Dict{String,Any}) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:9
 in parse(::Type{JSONRPC.Request}, ::String) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\jsonrpc.jl:37
 in run(::LanguageServer) at C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\languageserver.jl:28
 in include_from_node1 at .\loading.jl:488
 in process_options at .\client.jl:262
 in _start at .\client.jl:318
while loading C:\Users\10189524\.vscode\extensions\julialang.language-julia-0.5.1\scripts\languageserver\main.jl, in expression starting on line 41
[Error - 오후 11:37:31] Connection to server got closed. Server will not be restarted.

Is there some fault of my system?

Thanks

**Comment by ZacLN** [comment]
I think this bug was fixed on master. It's a it of a fiddle to install at the moment though. We should have a new release soon

**Comment by davidanthoff** [comment]
I'm closing this because we believe this is fixed for v0.6.0. We will have a beta out today and hopefully a final release next week. If you still see this once you have installed v0.6.0 of the extension, please ping us here!
