### ISSUE TITLE
IntelliSense and Go to definition don't work for modules other than Base on Win10

### ISSUE THREAD

**Issue by AStupidBear** [JuliaEditorSupport/julia-vscode#152]
![2017-04-07_190113](https://cloud.githubusercontent.com/assets/16422976/24797709/0e7c9ff2-1bc5-11e7-82f3-946b300b1866.jpg)

**Comment by davidanthoff** [comment]
Yes, this is a known limitation. The next version should address these issues, but it will be a while until that gets released.

**Comment by davidanthoff** [comment]
I just tried this on v0.6.0 and it seems to work, so I'm closing this. We are releasing a beta today, if you still see this problem on v0.6.0 beta or newer, please report back here.

**Comment by AStupidBear** [comment]
Thanks! However, the autocompletion is very slow.

**Comment by AStupidBear** [comment]
The IntelliSense is very slow and crashes a lot. Have you experienced that?

**Comment by ZacLN** [comment]
It should be in the region of 1-10ms for any hover/completion/signature after JITing + whatever the fixed vscode delay. 
Whats your computer set up, and are there any particular examples?

**Comment by AStupidBear** [comment]
![vscode](https://user-images.githubusercontent.com/16422976/27522543-81d6c234-5a59-11e7-80df-4b684a0de2c6.gif)

**Comment by AStupidBear** [comment]
The autocompletion is always slower than my typing even after the precompilation and parsing.
