### ISSUE TITLE
Evaluating code into module

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#153]
Sorry if this is a dup of something.

In Juno, it is possible to set the "active module", such that all code that is executed gets evaluated into that module.
That creates for a very nice work flow where changes made inside the code of a package gets "updated" by evaluating new code into that module.
There is then basically never a need to restart Julia when developing a package (which at least I used to do very frequently).
It would be nice to support this in julia-vscode.

Assuming I read things correctly, it would simply be to change the module in https://github.com/JuliaEditorSupport/julia-vscode/blob/86b91dce5f4a8218db79c954b59c711021386edb/scripts/terminalserver/terminalserver.jl#L39 from the hardcoded `Main` to the module currently set by the user.

**Comment by davidanthoff** [comment]
That has long been on my wishlist, but right now it is blocked by #105.

At this point we are actually not using the stuff in ``terminalserver.jl`` at all, instead we are just sending any code as copy-paste to the REPL... I just left ``terminalserver.jl`` there so that we can use it once #105 is fixed.

**Comment by davidanthoff** [comment]
@KristofferC Actually, I just realized that you are the author of https://github.com/KristofferC/OhMyREPL.jl. So maybe you are actually someone who understands the REPL code? Maybe you can help us with #105? That would be fantastic!

**Comment by KristofferC** [comment]
I think the way to get `s` (as we talked about during JuliaCon) is with the patch described at https://github.com/JuliaLang/julia/issues/13356#issuecomment-264377033. Otherwise the state lives locally in a function so it seems hard to access.

**Comment by ZacLN** [comment]
Having had a look at https://github.com/tshort/REPLinModule.jl,

```
function change_module(newmodule::Symbol)
    repl = Base.active_repl
    main_mode = repl.interface.modes[1]
    if !isdefined(Main, newmodule)
        info(string(newmodule, " not found"))
        return
    end
    main_mode.on_done = Base.REPL.respond(repl,main_mode; pass_empty = false) do line
        if !isempty(line)
            :( eval($newmodule, parse($line)) )
        else
            :(  )
        end
    end
end
```
should be what we need along with a listener on `_vscodeserver.conn` to check for changes to the active module and the ability for `vscode` to request a list of current namespaces?

**Comment by ZacLN** [comment]
PR https://github.com/JuliaEditorSupport/julia-vscode/pull/260
