### ISSUE TITLE
No code completion for v0.6.0-alpha.1

### ISSUE THREAD

**Issue by AStupidBear** [JuliaEditorSupport/julia-vscode#157]
I just download language-julia-0.6.0-alpha.1.vsix and find that there are no code completions even for Base functions.

![image](https://cloud.githubusercontent.com/assets/16422976/25570269/f5d53010-2e55-11e7-8b01-aa1e9271e483.png)

**Comment by davidanthoff** [comment]
Yeah, it is an alpha that is not very functional. I would not recommend it for normal use at this point, the last released version should work much better.
