### ISSUE TITLE
some depwarns on packages

### ISSUE THREAD

**Issue by musm** [JuliaEditorSupport/julia-vscode#160]
```
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

also running the install script gives
Error installing vscode.d.ts: Missing VSCode engine declaration in package.json.

**Comment by davidanthoff** [comment]
@musm At what step are you seeing these messages? I assume not at run time, but when you are setting up a dev environment?

**Comment by musm** [comment]
Yeah at a dev environment. Have not' tested in a while so they may already be fixed.

**Comment by davidanthoff** [comment]
Ok, I think that is mainly beyond our control, i.e. I also always see some dep warnings in the whole npm package ecosystem. I think unless this results in a bug we should just ignore, so I'm closing this for now.
