### ISSUE TITLE
display shift in terminal

### ISSUE THREAD

**Issue by AStupidBear** [JuliaEditorSupport/julia-vscode#169]
![2017-06-02_104736](https://cloud.githubusercontent.com/assets/16422976/26709136/ff503be4-4782-11e7-9e13-ea45a5d039e8.jpg)

As you can see, the result of `a + a` gradually shifts to the left. My julia version is v0.5.2 and I'm on Win10. Do you have such a problem? Is is due to vscode terminal or Julia REPLE?

**Comment by davidanthoff** [comment]
Hm, I can't reproduce this on my system. We are going to release a beta of v0.6.0 today, would be great if you could try things with that version, hopefully this just resolved itself.

**Comment by AStupidBear** [comment]
This is fixed by the recent update of Win10.

**Comment by davidanthoff** [comment]
Great, thanks for reporting back!
