### ISSUE TITLE
[v0.6] Intellisense should offer completion for `end`

### ISSUE THREAD

**Issue by helgee** [JuliaEditorSupport/julia-vscode#183]
I am currently on v0.6-beta1 and I think the new release will turn out great! There is an issue when the extension is used together with [vscode/Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim), though.

Steps to reproduce:

- Start typing any code block in insert mode.
- Reach the `end`.
- Intellisense offers completion to `endof`.
- There are now two options which are both less than optimal:
    - Press ENTER and get `endof`
    - Or press ESC to dismiss Intellisense but get dropped out of insert mode at the same time

![complete-end](https://user-images.githubusercontent.com/1408922/27066648-e0f4bfcc-5005-11e7-9043-5dced3bd3188.gif)

The behaviour is actually the same in the original Vim but there it is less of issue because auto-completion is mostly triggered manually.

An easy fix would be to offer `end` as an auto-complete option.

**Comment by ZacLN** [comment]
Yep this is annoying, PR to fix [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/84)

**Comment by ZacLN** [comment]
[This](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/84) is the fix
