### ISSUE TITLE
Spurious "Missing white space around operator" message for default/keyword arguments

### ISSUE THREAD

**Issue by helgee** [JuliaEditorSupport/julia-vscode#184]
![grafik](https://user-images.githubusercontent.com/1408922/27074483-8956d2ba-5027-11e7-975f-a37c33ca6093.png)

**Comment by helgee** [comment]
This also affects auto-formatting.

**Comment by ZacLN** [comment]
This is asking for white space around the `=`. I've seen both with and without used but is there a consensus for none when in function signatures?

**Comment by davidanthoff** [comment]
I use non in function signatures, but not sure whether that is widely shared... 

Maybe we can take a look at Julia base and follow whatever style they are using?

**Comment by helgee** [comment]
I had a look at base before I opened the issue and have not found any arguments with white space.

**Comment by ZacLN** [comment]
OK then, this'll need changing on the CSTParser side so will take a bit more time

**Comment by ZacLN** [comment]
fixed: https://github.com/ZacLN/CSTParser.jl/commit/08120387e3d84474e8705272ac331da7f8e34284

Change will take place when we update the submodules, if you want it in the meantime pull the master branch in your equivalent of  `.vscode/extensions/julia-vscode/scripts/languageserver/packages/CSTParser`

**Comment by davidanthoff** [comment]
We should probably do a beta 2 at the end of the week and then release next week.
