### ISSUE TITLE
Document sync between client and server is failing

### ISSUE THREAD

**Issue by staticfloat** [JuliaEditorSupport/julia-vscode#187]
As I'm typing my code within vscode, I often run into "parsing failure" errors that cause my entire file to get little red squigglies underneath it, which are removable only by reloading the VS Code window.  This happens fairly regularly as I edit large files, but is difficult to reproduce exactly.

**Comment by davidanthoff** [comment]
Hm, I guess this is difficult for us to address without a repo case... We did discuss that it would be nice if the red squiggles were less pervasive if the parser fails on the whole file.

**Comment by staticfloat** [comment]
@ZacLN showed me how to enable debug mode on my machine, so if I can get it to do it while debug mode is turned on, I'll give you more info.

**Comment by ZacLN** [comment]
This isn't actually related to the parser, theres a problem with the documentDidChange request handler

**Comment by staticfloat** [comment]
I got it to happen again.  At first, it froze with red squigglies everywhere, but when I opened the `Output` window to take a look at the logs, it cleared away the red squigglies.  It then stopped linting my Julia code all together for many minutes until I manually reloaded the window.  [Here's my log](https://gist.github.com/staticfloat/2830edff3b6b2b567f14bb540589d6f7), sorry it's so long.

**Comment by ZacLN** [comment]
Thanks, I'm going to get to the bottom if this tomorrow

**Comment by davidanthoff** [comment]
@ZacLN @staticfloat: This is fixed, right? I'm closing for now, but please reopen if that is premature.

**Comment by ZacLN** [comment]
Yep, done
