### ISSUE TITLE
Language Server cannot load Knet.jl

### ISSUE THREAD

**Issue by AStupidBear** [JuliaEditorSupport/julia-vscode#196]
This [line](https://github.com/denizyuret/Knet.jl/blob/master/src/karray.jl#L349) blocks the language server from loading Knet.jl. It said `cannot find METADATA.jl`

**Comment by ZacLN** [comment]
I can't replicate this, think it may be fixed on master by [this](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/94)

**Comment by AStupidBear** [comment]
Thanks! Now the only way for me to get around this is to comment the corresponding block until the next release.
