### ISSUE TITLE
split language server to package

### ISSUE THREAD

**Issue by ZacLN** [JuliaEditorSupport/julia-vscode#20]
Might we want to split the language server Julia code into a different repo leaving just the startup, version checking and package installation magic in here?

**Comment by davidanthoff** [comment]
Yes, definitely. But maybe first merge things here and release a version, and then move things out in a second step? I find it easier to develop while things are all in one repo, but once things mostly work we can move things into a separate repo.

That should then also just be a julia package, probably named ``LanguageServer.jl``, I can create that under the JuliaEditorSupport organization here. And then hopefully other packages can use it as well.

Another point there is to coordinate with the Juno work.

**Comment by davidanthoff** [comment]
I've now created a new repo for this: https://github.com/JuliaEditorSupport/LanguageServer.jl

I'll also start to create a branch here that uses that, once we have released v0.5.0 we can than merge that stuff into master.

**Comment by davidanthoff** [comment]
This is done.
