### ISSUE TITLE
Add user option to enable debug mode

### ISSUE THREAD

**Issue by ZacLN** [JuliaEditorSupport/julia-vscode#203]
To ease bug reporting

**Comment by davidanthoff** [comment]
I wish there was some API in VS Code that we could use for automatic crash reporting etc...

Another option would be to have a user option that saves the whole LS server output into a log file, and then folks could upload the log file directly?

**Comment by ZacLN** [comment]
Possibly, but someone was finding debug mode a major drag on performance (with atom, I think)

**Comment by davidanthoff** [comment]
Yeah, lets just start with a debug mode switch as this issue suggests.

**Comment by ZacLN** [comment]
We have both logging and crash reporting
