### ISSUE TITLE
Strip out (::Type{T})(arg) definition for types

### ISSUE THREAD

**Issue by quinnj** [JuliaEditorSupport/julia-vscode#205]
When doing `cmd + click` on a type, it often lists the `(::Type{T})(arg) where {T} = convert...` definition in sysimg.jl first (along w/ preview, see screenshot below). This is obviously not very helpful and leads to the need for extra clicks to get to the correct definition. Can that definition just be manually stripped in the results? That'd be helpful.

![screen shot 2017-07-13 at 2 32 48 pm](https://user-images.githubusercontent.com/2896623/28186443-69cb3c4c-67d8-11e7-9a46-d3e466164b18.png)

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/133
