### ISSUE TITLE
Plot in separate window?

### ISSUE THREAD

**Issue by guihigashi** [JuliaEditorSupport/julia-vscode#207]
Is it possible to disable the plot plane and have it show in separate windows?

**Comment by davidanthoff** [comment]
Not currently, right now the plot pane captures all plotting.

We should have many more options around that: a user setting, and some temporary way to switch a running session. Not sure when we'll be able to implement that.

**Comment by ZacLN** [comment]
You can just launch a standard terminal running Julia rather than using the `startREPL` command

**Comment by guihigashi** [comment]
@ZacLN I asked the question for 3 **personal** reasons:
1. I enjoyed a lot the flow of writing code, Ctrl+Enter and check;
2. I mainly use PyPlot and its Qt backend got some features already;
3. I find better if the editor window and REPL don't resize or anything, somehow I find it annoying (probably need medical help on that).

If I got it right. Did you mean "run the whole file on Julia terminal"? Or something else?

**Comment by ZacLN** [comment]
The vscode plot window only gets used if run the specific `language-julia.startREPL`

**Comment by davidanthoff** [comment]
There is actually another workaround: You can call ``Base.Multimedia.popdisplay()`` in the REPL until it pops the ``_vscodeserver.InlineDisplay()`` display. Once that is no longer on the display stack, things should fall back to the normal display method of the plotting package.

This is a bit of a hack and will probably stop working at some point, but until we provide a proper fix for this scenario, this might work.

**Comment by guihigashi** [comment]
thank you so much for both solutions
