### ISSUE TITLE
Using Base.Test does not make @test declared

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#209]
Even though the testing framework is used there is still a possible use of undeclared variable warning for `@test`.

**Comment by ZacLN** [comment]
immediate [fix](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/120), a proper fix needs a bit more thinking time

**Comment by davidanthoff** [comment]
@ZacLN We'll leave this open until there is a proper fix, but put it onto the backlog, i.e. we won't target this for v0.7, right?

**Comment by ZacLN** [comment]
Yep,

**Comment by ZacLN** [comment]
[fix](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/168)
