### ISSUE TITLE
Reload packages

### ISSUE THREAD

**Issue by cossio** [JuliaEditorSupport/julia-vscode#210]
julia-vscode highlights a variable when is used without declaring first. I am working on a package, so I declared some new variables there. But on the script file (where I am using the package), julia-vscode keeps highlighting these variables as non-existent. I think vscode is stuck with the earlier version of the package. How can I make it so that vscode syntax highlighter "reloads" the package and realizes the changes?

Right now what I do is reload the window... but that is overkill since it reloads EVERYTHING and unnecessarily slow. There should be a way to just reload one package.

**Comment by ZacLN** [comment]
Yup, seems like a good idea:
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/124
https://github.com/JuliaEditorSupport/julia-vscode/pull/211

**Comment by cossio** [comment]
Wow that was quick, thanks!

**Comment by ZacLN** [comment]
No problem! I've made a [wiki](https://github.com/JuliaEditorSupport/julia-vscode/wiki/Updating-to-the-lastest-julia-vscode) on how to get the master version of julia-vscode  up and running if you want to try it out (normal proviso about possible instability)

**Comment by davidanthoff** [comment]
At some point we should probably try to automate this step. Lets leave this issue open and on the backlog for that.

**Comment by ZacLN** [comment]
The ClobberingReload package seems to have some system for this

**Comment by ZacLN** [comment]
Closing, this issue will be addressed in our SymbolServer discussion
