### ISSUE TITLE
\dot causes preceding spaces to shrink

### ISSUE THREAD

**Issue by rdeits** [JuliaEditorSupport/julia-vscode#212]
Try typing the following into a Julia file in vscode:

```julia
function foo()
    x = 1
end

function foo()
    ẋ = 1
end
```

(where `ẋ` is typed as `x\dot<tab>`)

The result I see is this:

![screenshot from 2017-07-24 15 52 33](https://user-images.githubusercontent.com/591886/28541951-a517258c-7088-11e7-95a1-a8438c1ca393.png)

The indentation for both functions is actually exactly the same (4 spaces), but in the second case the spaces have...shrunk. I can verify that all 4 spaces are there by moving through them with the arrow keys, but they render at half width for some reason. 

This is not a major problem, but I just thought I'd report it anyway. Thanks for all your hard work!

**Comment by ZacLN** [comment]
Hmm, that's odd and annoying. I think this may be an upstream/font display issue. Are they still mis-aligned if you change the language-mode from Julia to something else?

**Comment by tkoolen** [comment]
I had already opened an issue for this: https://github.com/Microsoft/vscode/issues/31068.

**Comment by tkoolen** [comment]
This has been resolved upstream.
