### ISSUE TITLE
Add command to add package to current workspace

### ISSUE THREAD

**Issue by Keno** [JuliaEditorSupport/julia-vscode#214]
I see that there's a "julia: Open package directory in New Window" option. What I'd like is an option to add a package to the current workspace (like the "Add folder to current workspace" option).

**Comment by ZacLN** [comment]
We're waiting on https://github.com/Microsoft/vscode/issues/396 I think. I shouldn't be much work on this side of things

**Comment by davidanthoff** [comment]
Yes, this is blocked upstream. My understanding is that this will come rather soon, though, it seems this is the big feature they are working on for VS Code.

**Comment by ZacLN** [comment]
We really needs to get the multi-thread/process stuff up and running for this to be workable

**Comment by davidanthoff** [comment]
I took a picture of the whiteboard stuff we drew during your visit, I'll post that soon here!
