### ISSUE TITLE
Next line indents if "type" is anywhere in previous line

### ISSUE THREAD

**Issue by quinnj** [JuliaEditorSupport/julia-vscode#216]
I'm guessing this is tied somehow to the fact that you usually want to auto-indent when writing something like
```julia
type Foo
    autoindentedfield::String
...
```
but it's a bit annoying when doing something like
```julia
type Foo
    footype::String
        nowthisfieldisauto_indented::String
...
```

**Comment by davidanthoff** [comment]
Uh, this is quite bad, it actually gets triggered by lots of keywords, not just ``type``...

That behavior is controlled by [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/src/extension.ts#L163). Main problem is that my regex foo is not really existent... The discussion in JuliaEditorSupport/Julia-sublime#44 might also help.

I'll ask for help on slack, maybe there are some folks that have a better regex grasp than me.
