### ISSUE TITLE
Linter doesn't use proper column numbers

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#22]
The proper way to do this is to use something like [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/450a76fee778119c3c843dc4564d21a0050ac0ff/scripts/languageserver/lint.jl#L18) for the ``character`` field of the ``start`` part of the range, and then ``typemax(Int)`` for the ``character`` field of the ``end`` part of the range, like [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/450a76fee778119c3c843dc4564d21a0050ac0ff/scripts/languageserver/lint.jl#L21).

**Comment by ZacLN** [comment]
You fixed this

**Comment by davidanthoff** [comment]
Now properly fixed.
