### ISSUE TITLE
v0.7.0 beta 2 spurious errors

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/julia-vscode#220]
Still getting spurious "Possible use of undeclared variable" messages with the beta (perhaps this wasn't supposed to have been resolved?).

Specifically,

Anything in tests that starts `@test`, `PriorityQueue` and `dequeue_pair` (from DataStructures) in LightGraphs `src/shortestpaths/dijkstra.jl`.

**Comment by davidanthoff** [comment]
@ZacLN will know whether we tried to fix this or deferred to the next release :)

**Comment by sbromberger** [comment]
Ah, this should probably have been in LanguageServer, right? If so, my apologies and I'll close it out.

**Comment by davidanthoff** [comment]
No no, no worries, main thing is that we get these reports, doesn't matter much where you open issues :) Both @ZacLN and I monitor both places.

**Comment by sbromberger** [comment]
Ok, thanks. I was a bit puzzled as to why I couldn't find my old "spurious warning" issues - then I realized – I'm in the wrong damn repo.

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/146 should do it
