### ISSUE TITLE
linter does not handle iterator functions

### ISSUE THREAD

**Issue by Ken-B** [JuliaEditorSupport/julia-vscode#221]
I don't know the correct name for this in julia, but this is valid syntax:
```julia
f(x) = sum(x * i for i = 1:10)
```
however the linter gives a "Possible use of undeclared variable i" warning.

Thanks!

**Comment by ZacLN** [comment]
fix: https://github.com/ZacLN/CSTParser.jl/commit/d8188d30d6b52ef46471ec726db5a832d1e71a37

**Comment by Ken-B** [comment]
wow, amazingly fast fix, thanks!
