### ISSUE TITLE
linter doesn't handle `using PACKAGE: foo` and later `PACKAGE.bar`

### ISSUE THREAD

**Issue by Ken-B** [JuliaEditorSupport/julia-vscode#222]
This is valid syntax (just an example, works with other packages)
```julia
using Optim: minimizer
res = Optim.optimize(x->sum(x.^2), ones(2))
minimizer(res)
```
but the linter gives an "Possible use of undeclared variable Optim" warning.

Thank you.

**Comment by ZacLN** [comment]
Oops, I wasn't aware of that syntax. I'll push a fix later today

**Comment by ZacLN** [comment]
fix: https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/152

**Comment by Ken-B** [comment]
I've just noticed the issue is more complex than this. The given syntax is allowed in the REPL (global namespace) but not inside a module.
So the same example as above inside a module
```julia
module Foo
    using Optim: minimizer
    res = Optim.optimize(x->sum(x.^2), ones(2))
    minimizer(res)
end
```
gives  `ERROR: UndefVarError: Optim not defined`.

@ZacLN sorry for the confusion, it seems the original linter was correct, could you revert?

**Comment by ZacLN** [comment]
No problem, I'll revert for the next release

**Comment by ZacLN** [comment]
[fix](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/168)
