### ISSUE TITLE
Crash when loading QML.jl

### ISSUE THREAD

**Issue by barche** [JuliaEditorSupport/julia-vscode#223]
When opening the QML.jl source tree I get this error from the language server on linux:

```text

signal (6): Aborted
while loading /home/username/.julia/v0.6/QML/src/QML.jl, in expression starting on line 522
gsignal at /usr/bin/../lib/libc.so.6 (unknown line)
abort at /usr/bin/../lib/libc.so.6 (unknown line)
_ZNK14QMessageLogger5fatalEPKcz at /usr/lib/libQt5Core.so.5 (unknown line)
_ZN14QXcbConnectionC1EP19QXcbNativeInterfacebjPKc at /usr/bin/../lib/libQt5XcbQpa.so.5 (unknown line)
_ZN15QXcbIntegrationC2ERK11QStringListRiPPc at /usr/bin/../lib/libQt5XcbQpa.so.5 (unknown line)
unknown function (ip: 0x7f67491e21bd)
_ZN27QPlatformIntegrationFactory6createERK7QStringRK11QStringListRiPPcS2_ at /usr/lib/libQt5Gui.so.5 (unknown line)
_ZN22QGuiApplicationPrivate25createPlatformIntegrationEv at /usr/lib/libQt5Gui.so.5 (unknown line)
_ZN22QGuiApplicationPrivate21createEventDispatcherEv at /usr/lib/libQt5Gui.so.5 (unknown line)
_ZN23QCoreApplicationPrivate4initEv at /usr/lib/libQt5Core.so.5 (unknown line)
_ZN22QGuiApplicationPrivate4initEv at /usr/lib/libQt5Gui.so.5 (unknown line)
_ZN19QApplicationPrivate4initEv at /usr/lib/libQt5Widgets.so.5 (unknown line)
_ZN7qmlwrap18ApplicationManager16init_applicationEv at /home/username/src/julia/QML/deps/usr/lib/libqmlwrap.so (unknown line)
_ZN5jlcxx6detail11CallFunctorIvJEE5applyEPKv at /home/username/src/julia/QML/deps/usr/lib/libqmlwrap.so (unknown line)
init_application at ./<missing>:0 [inlined]
__init__ at /home/username/.julia/v0.6/QML/src/QML.jl:32
```
The crash appears to be related to Qt maybe because of a missing display or something when loading the module from within VSCode?

**Comment by ZacLN** [comment]
I can't replicate this, any ideas @davidanthoff ?

**Comment by davidanthoff** [comment]
Hm, this looks like a crash in some Qt libraries, right? I think fundamentally we need to solve this kind of issue by not loading any user packages ever into the language server process, i.e. by moving to the separate process model we discussed when we met. I don't really have a better idea right now.

I think we won't be able to fix this for v0.7.0, the separate process model is probably too much for this iteration.

**Comment by barche** [comment]
Yes, it's coming from `QMessageLogger::fatal`, which prints a fatal error message and then aborts the program, but I'm not sure what the actual message is, it doesn't seem to be printed to the Julia Language Server log panel. Come to think of it, maybe I can also add an error handler to QML.jl that catches this sort of thing without quitting Julia.

**Comment by davidanthoff** [comment]
Normal STDOUT is used for the communications between the LS and VS Code, so if this message is output to that, all bets are off. If that log message gets send to the error output stream, it should show up in the log, in theory :)

**Comment by barche** [comment]
Well, I'm not sure exactly what the message is, but I guess this was more a QML.jl issue after all. It seems it was safe to remove the `init_application` from `__init__`, so this is no longer an issue for me. Thanks for the help and sorry for the noise.

**Comment by davidanthoff** [comment]
Sure, no problem, any bug report is welcome!!
