### ISSUE TITLE
Couple of spurious undefined variable warnings in anonymous functions

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#224]
#![image](https://user-images.githubusercontent.com/1282691/28828625-8e559d5c-76d1-11e7-801f-555bd68022d6.png)

I believe this code should show zero undefined variable warnings.

For copy paste:

```jl
function f(x, o...; p...)
    return o, p
end

(x, o; p = 1) -> begin
    return o, p
end

(x, o...; p...) -> begin
    return o, p
end
```

**Comment by ZacLN** [comment]
https://github.com/ZacLN/CSTParser.jl/pull/35 should do it
