### ISSUE TITLE
auto-indentation by default or documented

### ISSUE THREAD

**Issue by Ken-B** [JuliaEditorSupport/julia-vscode#226]
I just discovered the auto indentation of the `end` keyword in #37 by setting `"editor.autoIndent": true`. Finally! 

Is it possible to have this behaviour as default? (Who wouldn't want this?!) Or at least document it somewhere, e.g. in the Readme?

Thanks!

**Comment by davidanthoff** [comment]
Given that this is a VS Code wide setting we shouldn't change that from our extension. I believe VS Code will actually switch this on by default in an upcoming release, so then this should be solved for good.

A PR to the README with this info would be welcome in the meantime!

**Comment by Ken-B** [comment]
I'll be happy to! See #228
