### ISSUE TITLE
Nested modules and defined variables

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#231]
![image](https://user-images.githubusercontent.com/1282691/28921486-6fb674d0-7856-11e7-9942-172d6f3bc2cd.png)

`HELLO` is defined in `B` because of the `using A`

For pasting:
```
module A
    export HELLO
    HELLO = 3
    module B
        using A
        print(HELLO)
    end
end;
```

**Comment by ZacLN** [comment]
This is going to have to wait for the next release

**Comment by ZacLN** [comment]
fixed in https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/168
