### ISSUE TITLE
Linting inside macros

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#232]
Since a macro works on syntax I don't think it is meaningful to do much linting inside macros.

For example:

```
@enum(ColorMode,
RESET,
COLORS_16,
COLORS_256,
COLORS_24BIT)
```

says that all the variables are undefined but the macro actually is there to define them.

**Comment by ZacLN** [comment]
In this case, yes in others (i.e. @inbounds, etc.) you'd then be missing out huge swathes of code. I'll look at all Base/Core exported macros and come up with a list that get bypassed

**Comment by KristofferC** [comment]
Ah, yes of course (with `@inbounds`). I think special casing is the way to go then. Maybe `@enum` should define the variables then?

**Comment by ZacLN** [comment]
Yep, if not overwritten

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/157
