### ISSUE TITLE
Spurious code never reached on elseif

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#233]
![image](https://user-images.githubusercontent.com/1282691/28922133-3dd54240-7859-11e7-9bb8-0114b7fec4c7.png)

**Comment by ZacLN** [comment]
A missalignment of diagnostic hove,r one sec

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/156
