### ISSUE TITLE
`local` leads to undef variable warning

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#235]
```jl
function f()
    local val
    val = 0
    return val
end
```

shows a warning of the `val` in `local val`. Perhaps it shouldn't.

**Comment by ZacLN** [comment]
It definitely shouldn't, cheers your being a demon on these bug finds!

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/158
