### ISSUE TITLE
Segfault (while parsing?)

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#236]
On julia-vscode 0.6.2, I reliably get the following segfault:
```
signal (11): Segmentation fault: 11
while loading /Users/twan/.vscode/extensions/julialang.language-julia-0.6.2/scripts/languageserver/main.jl, in expression starting on line 27
jl_array_ptr_ref at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:712 [inlined]
eval_import_path_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:363
eval_import_path at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:430 [inlined]
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:510
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/builtins.c:496
macro expansion at /Users/twan/.vscode/extensions/julialang.language-julia-0.6.2/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:33 [inlined]
#3 at ./event.jl:73
unknown function (ip: 0x11d6cee9f)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1424 [inlined]
start_task at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:267
Allocations: 13140858 (Pool: 13137782; Big: 3076); GC: 28
[Info  - 12:10:37 PM] Connection to server got closed. Server will restart.
```
on OSX,

```
signal (11): Segmentation fault
while loading /home/twan/.vscode/extensions/julialang.language-julia-0.6.2/scripts/languageserver/main.jl, in expression starting on line 27
eval_import_path_ at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:361
eval_import_path at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:430 [inlined]
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:510
jl_toplevel_eval_in at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:496
macro expansion at /home/twan/.vscode/extensions/julialang.language-julia-0.6.2/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:33 [inlined]
#3 at ./event.jl:73
unknown function (ip: 0x7fb56f39195f)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1424 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 13538325 (Pool: 13535060; Big: 3265); GC: 29
```
on Linux.

This occurs while parsing [RigidBodyDynamics.jl](https://github.com/tkoolen/RigidBodyDynamics.jl) code (last info before segfault: `INFO: parsed /Users/twan/code/julia/RigidBodyDynamics/v0.6/RigidBodyDynamics/test/test_util.jl`), on (for example) the `v0.2.0` tag

This is probably a Julia issue, but just wanted to document this here and check if any of you have experienced this before.

**Comment by tkoolen** [comment]
This happens on both OSX and Linux BTW.

**Comment by tkoolen** [comment]
I'm actually no longer sure if this occurs while parsing or after parsing is done. It seems that with a newly opened vscode, the crash doesn't happen until I ctrl+click on something. It would be nice to have an `INFO: done parsing` message to make sure.

**Comment by davidanthoff** [comment]
I think this is another instance where we load some user package into the LS process, and then that crashes the whole process. Maybe we should just have a real go for the next release cycle to remove any loading of user code in the LS process at all, that should make things much more stable. I'll try to find some time to investigate how complicated that would be.

**Comment by KristofferC** [comment]
I was actually under the assumption that everything was totally static analysis.

**Comment by ZacLN** [comment]
It happening after a Ctrl-click suggests @davidanthoff  is right, it causes a lint/scoping run that'll try to load modules as needed.

@KristofferC, modules loaded by `using` or `import` if not defined within the workspace just get imported to access variable information

**Comment by ZacLN** [comment]
Yep, this is the same thing
```
macro expansion at /Users/twan/.vscode/extensions/julialang.language-julia-0.6.2/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:33 [inlined]
``` 
is 
```
@eval import $modname
```

**Comment by tkoolen** [comment]
Thanks for following up. How would I go about creating a more minimal example so that I can report a Julia issue?

**Comment by ZacLN** [comment]
I found the problem, it was trying to run 
```
modname = :.
@eval import $modname
```
which was causing the segfault. I'll push a fix for us and open an issue upstream

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/163

**Comment by ZacLN** [comment]
upstream issue https://github.com/JuliaLang/julia/issues/23173

**Comment by tkoolen** [comment]
Thanks so much!
