### ISSUE TITLE
Weird parsing error

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#239]
![image](https://user-images.githubusercontent.com/1282691/28984413-25467568-795e-11e7-9f99-b441379d9bfc.png)

When upgrading the package Quaternions.jl to 0.7.

**Comment by KristofferC** [comment]
Not a parsing error, just the point where it gives up.

**Comment by ZacLN** [comment]
why is Dual undefined?

**Comment by KristofferC** [comment]
It shouldn't be.

**Comment by ZacLN** [comment]
nested module?

**Comment by KristofferC** [comment]
Hmm, it got defined after I fixed all the whitespace issue so it didn't give up.

**Comment by KristofferC** [comment]
FWIW: It also just fixed a bug: https://github.com/JuliaGeometry/Quaternions.jl/pull/23/commits/b320e5e1639632c808bd4081fce54e28bc43c34b :)

**Comment by ZacLN** [comment]
hmm, very strange. 

Nice on the bug catch!
