### ISSUE TITLE
Spurious undef variable warning in anonymous function

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#241]
![image](https://user-images.githubusercontent.com/1282691/28995607-75c709aa-79ed-11e7-948d-77b1398371e5.png)

**Comment by davidanthoff** [comment]
@ZacLN I've added to the v0.7.0 milestone, but please move to backlog if you want to fix this later.

**Comment by ZacLN** [comment]
[fix](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/168)
