### ISSUE TITLE
Control personal preferences for formatting diagnostics?

### ISSUE THREAD

**Issue by cormullion** [JuliaEditorSupport/julia-vscode#242]
I'm enjoying VSCode. The diagnostics that are generated are cool and very useful! But it would be nice to have some say in which issues were flagged and which weren't. For example, I like to write this:

```
starttextangle = the_angle - (theta/2) - lspacedangle/2
```

where there are some spaces around operators and some not. (I prefer my way, at the moment. Until that day comes when we all have to format our code "correctly" to some official standard... :))

So that particular rule could be optional...?

Similarly, the rule about commas; I prefer a space after a comma, but this warrants a warning:

```
polygonlist = Array{Point, 1}[]
```

even though that's obviously better with a space... :)

Is there a way? I can't think of a decent interface, though...

**Comment by ZacLN** [comment]
Formatting will be configurable in the next release. Could you copy this issue (and any other thoughts/requests) to [DocumentFormat.jl](https://github.com/ZacLN/DocumentFormat.jl/) please?

**Comment by cormullion** [comment]
@ZacLN Ooh, that looks good. :)
