### ISSUE TITLE
After installation, "Reload" button doesn't go away

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/julia-vscode#243]
See screenshot. Basically, I installed via VSIX, and exited/restarted VSCode, but the "Reload" button next to the extension doesn't go away.

<img width="205" alt="screen shot 2017-08-07 at 08 13 11" src="https://user-images.githubusercontent.com/941359/29033004-6e0e1f12-7b48-11e7-86ab-b12e53ac4e6d.png">

**Comment by tshort** [comment]
I think you have to completely delete the old one then reinstall it.

**Comment by davidanthoff** [comment]
Yeah, this is annoying, but as far as I can tell just a bug in VS Code itself... Might be a good idea to open an issue over in the vscode repo about this. A lot of folks seem to have this issue.

**Comment by sbromberger** [comment]
Closing because the best practice is to remove all earlier versions, which eliminates this issue.
