### ISSUE TITLE
`Error: The mode has failed while tokenizing the input.`

### ISSUE THREAD

**Issue by GlenHertz** [JuliaEditorSupport/julia-vscode#248]
I can get the Julia extension installed but syntax highlighting doesn't work.  I get the following error:

`Error: The mode has failed while tokenizing the input.`

If I do `a = 2+5 <C-Enter>` I get a Julia console and the correct output of the expression so it seems the extension is installed correctly.  Even if I have a file with one line in it I still get the error.

I'm using VS Code 1.14, julia-vscode 0.7, Julia 0.6, RHEL 6.6.

**Comment by davidanthoff** [comment]
That is very strange, a broken syntax highlighting almost sounds like a VS Code problem... Where and how does that message appear? A screenshot would be great.

**Comment by GlenHertz** [comment]
![image](https://user-images.githubusercontent.com/1714451/29091221-392692d0-7c50-11e7-8eeb-da68c4284065.png)

The error reappears about 6 times in succession (on the same spot).  

I think you are right about it being a VS Code issue.  If I open up a `json` file I get the same error.  In the xterm I get:

```
WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NAME_NOT_RESOLVED,
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NAME_NOT_RESOLVED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NAME_NOT_RESOLVED
[uncaught exception in main]: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (/home/hertz/a/RedHatEnterpriseWorkstation6.4/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:4:78286)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Should I punt this over to VS Code?  I'm not sure if GitHub has a way move an issue over.

**Comment by davidanthoff** [comment]
Ah, yes, if this also happens for JSON files, then it is definitely a VS Code issue unrelated to the julia extension. Yes, best to open an issue over at https://github.com/microsoft/vscode. I don't think there is a way to move issues.

Ideally you would open an issue over there and then mention this issue here, so that we keep track of what is going on with this.

**Comment by davidanthoff** [comment]
Ok, I'm closing this because they won't fix this upstream.
