### ISSUE TITLE
Highliting of strings trips over `$`

### ISSUE THREAD

**Issue by mauro3** [JuliaEditorSupport/julia-vscode#256]
Here two examples from https://github.com/MikeInnes/MacroTools.jl/blob/master/src/utils.jl

![a](https://user-images.githubusercontent.com/4098145/29314794-f7f7efd2-81bf-11e7-9a6b-386cd447a48a.png)
![b](https://user-images.githubusercontent.com/4098145/29314797-f973cbba-81bf-11e7-98fa-8ce1113e4bc1.png)

Note how in the second example even the end of the string `"""` is not recognized because it is not on a new line.

**Comment by davidanthoff** [comment]
We should try and see whether this works properly in Atom. I'm just periodically copying the syntax files from https://github.com/JuliaEditorSupport/atom-language-julia over to here, so ideally we would actually fix this over there (if this is a problem on that side as well) and then just make another copy.

**Comment by pfitzseb** [comment]
Yeah, this is an issue with `atom-language-julia`.

**Comment by pfitzseb** [comment]
This is fixed on language-julia 0.14, so you can update your syntax here as well :)

**Comment by davidanthoff** [comment]
TODO for v0.10.0
