### ISSUE TITLE
Loading a file with invalid Julia code can crash language server

### ISSUE THREAD

**Issue by mauro3** [JuliaEditorSupport/julia-vscode#257]
Loading a file which contains the (invalid) line `f(x::T) where Tr(T)<:Tr where T<:Integer= 1` crashes the Julia language server.  Eventually it gives up with "The julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

**Comment by ZacLN** [comment]
[fix](https://github.com/ZacLN/CSTParser.jl/commit/6673f7d9672b1d3bea23e8e7220eb39bad7d98b2)
