### ISSUE TITLE
Problems when extension starts with same file opened in two panes 

### ISSUE THREAD

**Issue by favba** [JuliaEditorSupport/julia-vscode#261]
I'm using julia-vscode v0.7.0 on Mac OSX.
This happens when my project session is saved with the same file opened on two panes.
When I open the session again the extension starts julia, but it never quits the `julia:busy` state and no syntax completion or other features are available.

![image](https://user-images.githubusercontent.com/17421145/29595459-8729145e-8785-11e7-9af2-b1c9e87b1fb3.png)

**Comment by ZacLN** [comment]
Hi, I can't replicate this could you [turn on debug mode](https://github.com/JuliaEditorSupport/julia-vscode/wiki/Manually-turning-on-the-debugger) and tell me what's happening?

**Comment by KristofferC** [comment]
Isn't this just the same problem with Julia getting stuck due to the asynchronous loading.

**Comment by ZacLN** [comment]
What async. loading?

**Comment by KristofferC** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/issues/255

**Comment by ZacLN** [comment]
Ah gotta, think you're right

**Comment by favba** [comment]
Well, this is strange. I turned on debug mode to collect info but I cannot reproduce the issue anymore. But it definitely looked like #255. I'll leave debug mode on so I can spot exactly when this happens...
Should I close this issue?

**Comment by ZacLN** [comment]
I think this is almost certainly #255 then, that was also difficult to replicated w/ debug mode on

**Comment by davidanthoff** [comment]
I'm closing this for now. Please reopen if this appears again.
