### ISSUE TITLE
Linter: duplicate argument names warning when argument names omitted

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#264]
```julia
function f(::Number, ::Number)
    nothing
end
```
results in `[LanguageServer.LSDiagnostic] Use of duplicate argument names`.

This is with LanguageServer `d7f5ea227b7afc945771c955a6b1205ed1b663b5`, CSTParser `cf374919080908d0dada1c14a66b328b0ef17016` (fairly recent master of both).

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/180
