### ISSUE TITLE
Ctrl + click in stack trace doesn't work if location is split across multiple lines

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#268]
If there is an exception e.g. while running tests, then ctrl + clicking on a location (such as "/home/twan/code/RigidBodyDynamics/v0.6/RigidBodyDynamics/src/mechanism_state.jl:603") that appears in the stack trace will usually take you to the correct file and line number. However, if the location happens to be split across multiple lines, then ctrl + clicking has no effect. This happens on Linux (but maybe also on other platforms).

**Comment by ZacLN** [comment]
This is an upstream issue I think, we don't have control over how links are followed outside of the editor window. I'll have a hunt for an issue and link it to here or open a new one

**Comment by ZacLN** [comment]
https://github.com/Microsoft/vscode/issues/33005

**Comment by davidanthoff** [comment]
I believe this should work with recent VS Code versions. If not, please reopen.

**Comment by tkoolen** [comment]
This is *not* working with recent VS Code versions. The linked upstream issue was closed as a duplicate, not because it was fixed.
