### ISSUE TITLE
`using` statements with relative module paths not handled correctly

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#276]
```julia
module A

module B
export foo
foo(x) = x
end

using .B
bar(x) = foo(x)

end
```
results in 'Possible use of undeclared variable foo'. However, changing `using .B` to `using A.B` works.

Similarly,
```julia
module A

export foo
foo(x) = x

module B
using ..A
bar(x) = foo(x)
end

end
```
results in the same behavior.

**Comment by ZacLN** [comment]
I've added a [fix](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/195) for the first simple case above, I'll have a look at it in more detail in a bit

**Comment by tkoolen** [comment]
Great, thanks!

**Comment by davidanthoff** [comment]
@ZacLN is there still a complicated case to be handled? Should we move that to the backlog?

**Comment by ZacLN** [comment]
push this back for v0.11.0/StaticLint

**Comment by ZacLN** [comment]
fixed
