### ISSUE TITLE
Is there a way to disable linting for an entire directory (tree)?

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/julia-vscode#279]
The linter currently can't make sense of the way we have our tests or benchmarks set up. Is there a way to specify "don't lint anything in the `test/` or `benchmarks/` directory trees?"

**Comment by ZacLN** [comment]
Yup, I missed a PR for the beta, I've added the relevant PRs [here](https://github.com/JuliaEditorSupport/julia-vscode/pull/281) and [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/197)

There's an 'ignore' option when right clicking on the file/folder in the explorer.

**Comment by sbromberger** [comment]
@ZacLN the "ignore" option is in the beta, it just didn't seem to work.

**Comment by ZacLN** [comment]
Yep I missed out a connecting function

**Comment by sbromberger** [comment]
Ok, cool. Thank you. :)

**Comment by sbromberger** [comment]
@ZacLN is there a branch I can check out to test this?

**Comment by davidanthoff** [comment]
We're releasing another beta today, I assume that will have it.

**Comment by sbromberger** [comment]
Closing in favor of #323
