### ISSUE TITLE
Support region markers

### ISSUE THREAD

**Issue by innerlee** [JuliaEditorSupport/julia-vscode#282]
It will be supported in the next release.
See https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_17.md#folding-regions

**Comment by ZacLN** [comment]
Suggestions for labels used?

**Comment by KristofferC** [comment]
`#==#` with arbitrary many `=`?

**Comment by davidanthoff** [comment]
We should probably coordinate with the Juno folks, so that we use the same style.

**Comment by innerlee** [comment]
I'm happy with `#region` and `#endregion`
