### ISSUE TITLE
`local` doesn't define a variable

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#284]
Similar to #235 but not the same. Also, not sure if this is fixed but:

![image](https://user-images.githubusercontent.com/1282691/31070984-b7b3efc0-a762-11e7-9edd-f68484fa52be.png)

`index` is shown as undefined variable.

**Comment by ZacLN** [comment]
I can't replicate

**Comment by KristofferC** [comment]
Ok will check again.

**Comment by KristofferC** [comment]
Actually this is an issue. It happend with the `? :` syntax:

```
function f(y)
    local weights = 2
    weights == 1 ? 2 : 3
end
```

`weights` is here shown as undef.

**Comment by ZacLN** [comment]
As per the other issue (do do with warnings offset) it's fixed by https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/199

**Comment by ZacLN** [comment]
I've fixed the offsets 
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/209
