### ISSUE TITLE
Wrong locations in undef var errors

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#285]
The following code:

```
function lcs(old_tokens::Vector, new_tokens::Vector)
    local m = length(old_tokens)
    local n = length(new_tokens)
    local weights = zeros(Int, m + 1, n + 1)
    for i = 2:(m + 1), j = 2:(n + 1)
        weights[i, j] = old_tokens[i - 1] == new_tokens[j - 1] ?
            weights[i - 1, j - 1] + 1 : max(weights[i, j - 1], weights[i - 1, j])
    end
    return weights
end
```

has misplaced locations for the (spurious) undef var errors:

![image](https://user-images.githubusercontent.com/1282691/31071724-65001a94-a765-11e7-9a71-f507505692b5.png)

**Comment by KristofferC** [comment]
The problem is with the double loop.  Here is a smaller example:

```
function f()
    local VVVVVVVV
    for i = 2:3, j = 2:4
        VVVVVVVV == 1 ? VVVVVVVV : 3
    end
    return VVVVVVVV
end
```

![image](https://user-images.githubusercontent.com/1282691/31113336-1f083d82-a819-11e7-9f0a-2e66dedb2fa4.png)

**Comment by ZacLN** [comment]
Yep the linting offsets is skipping one part of the `Block` range

**Comment by ZacLN** [comment]
fixed
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/209
