### ISSUE TITLE
Multiple argument to `using` does not define all module names

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#286]
![image](https://user-images.githubusercontent.com/1282691/31113658-91538184-a81a-11e7-9760-f20f2b4bddbe.png)

`BlockArrays` is undef but shouldn't be.

**Comment by ZacLN** [comment]
Works for me. Obvious question but are you sure it's installed?

**Comment by ZacLN** [comment]
Is this still a problem?

**Comment by KristofferC** [comment]
No,
