### ISSUE TITLE
Keep focus in editor when running code?

### ISSUE THREAD

**Issue by mpastell** [JuliaEditorSupport/julia-vscode#293]
I upgraded to 0.8 beta and noticed that running code in editor now moves the focus to terminal. Is there way to disable that and keep focus in the editor? It would be nice to have that as an option.

Many thanks for the excellent work, this is definitely my favorite way to write Julia.

**Comment by ZacLN** [comment]
This should already be the case, are you using beta.4?

**Comment by mpastell** [comment]
Yes, 0.80-b4 with VSCode 1.17.0 on Windows.

**Comment by davidanthoff** [comment]
Alright, I think I fixed this. If this is still the case with the next beta, please reopen the issue.

**Comment by mpastell** [comment]
Thanks, this is fixed for me using 0.8.0-rc3
