### ISSUE TITLE
Wrong spans for warning about exporting a symbol too many times

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#300]
![image](https://user-images.githubusercontent.com/1282691/31583393-2bc0c4fa-b19b-11e7-895d-02f8913c7b53.png)

Variables `FileDownloader`is double exported but the warning span is off.

**Comment by ZacLN** [comment]
fixed, https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/206
