### ISSUE TITLE
Fix all similar deprecations doesn't really work anymore.

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#301]
See http://www.giphy.com/gifs/3ov9jFP5Wmr7tZH1IY.

Pressing to fix all deprecations seems to do something (since the warnings are changing) but it definitely doesn't seem to fix all of them.

Actually, you can see in the video that the struct on the very bottom gets fixed but not the one I am clicking on.

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/pull/305s should do it

**Comment by davidanthoff** [comment]
@ZacLN can we close this one?
