### ISSUE TITLE
using inside an expression

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#302]
![screen shot 2017-10-15 at 12 27 05](https://user-images.githubusercontent.com/1282691/31583926-3d56e25e-b1a4-11e7-832a-7cecfbc73779.png)

I think this should define WinRPM.

**Comment by ZacLN** [comment]
Can't replicate, does hovering over WinRPM in the `using` statement give you anything?

**Comment by ZacLN** [comment]
Did u check this @KristofferC ?

**Comment by KristofferC** [comment]
I didn't have WinRPM installed. Hm, I mean the code is syntactically correct, it is just the I am missing a library. Perhaps a different warning should be used? Anyway, closing.

**Comment by davidanthoff** [comment]
I'm closing this, if that is not what you wanted @KristofferC please reopen!
