### ISSUE TITLE
REPL Variables Panel wraps unnecessarily

### ISSUE THREAD

**Issue by ssfrr** [JuliaEditorSupport/julia-vscode#306]
See the image below, where the `ans` variable is broken onto two lines for some reason. I don't think it's length wrapping because the line above is longer, maybe because there's a space?

![image](https://user-images.githubusercontent.com/734386/31589165-f3cee6c8-b1ca-11e7-9331-47ba10dd15a7.png)

This is on:
vscode 1.17.1
julia-vscode 0.8.0-beta4
julia 0.6.0
on Linux

**Comment by davidanthoff** [comment]
I'm pretty sure that this is out of our control, right @ZacLN?

**Comment by KristofferC** [comment]
Probably https://github.com/JuliaEditorSupport/julia-vscode/blob/e861e2ada97e72960e03b2e6ec79426169327940/src/repl.ts#L106

**Comment by ZacLN** [comment]
Yep, it's that

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/pull/330

**Comment by ssfrr** [comment]
Woot, thanks!
