### ISSUE TITLE
set execution module automatically based on code location

### ISSUE THREAD

**Issue by ssfrr** [JuliaEditorSupport/julia-vscode#308]
This came up on Slack but I figured I'd track it as an issue.

It would be great if julia-vscode automatically set the execution module based on where they code you're executing is.

Often I'll be working one a package in the editor, and doing one-off testing in the REPL (or in a scratch editor window). Currently each time I want to change a method definition in the package I have to manually switch to that module, run the code, switch the module back to `Main`, and run the test code in that context.

**Comment by KristofferC** [comment]
FWIW, for this type of workflow I use Revise.jl.

**Comment by davidanthoff** [comment]
@ZacLN Do you intent to implement this for v0.8.0 or later? I've added it to v0.8.0 for now, you can obviously move it to another milestone as you see fit :)

**Comment by davidanthoff** [comment]
I'll move this to v0.9.0 for now, I think we should mainly just try to get v0.8.0 out at this point. If anyone submits a PR for this before we cut the next beta (hopefully the last one) we can still include it, but otherwise I'd say we move it to v0.9.0.

**Comment by ZacLN** [comment]
I've added configuration option to use Revise
