### ISSUE TITLE
"Change REPL Module" command moves focus to REPL

### ISSUE THREAD

**Issue by ssfrr** [JuliaEditorSupport/julia-vscode#309]
I guess this command might be used explicitly less often if #308 is implemented, but currently if your cursor is in an editor and you run the "Change REPL Module" command it moves focus to the REPL pane.

**Comment by ZacLN** [comment]
commit added to https://github.com/JuliaEditorSupport/julia-vscode/pull/295

**Comment by ChristianKurz** [comment]
I got the problem the other way round:

Focus is stolen from the REPL using `Change REPL Module`. I think the command should just save focus location and restore it afterwards.

**Comment by davidanthoff** [comment]
@ChristianKurz could you open a new issue for this? It seems a distinct point. Thanks.
