### ISSUE TITLE
highlight `isa` keyword

### ISSUE THREAD

**Issue by ssfrr** [JuliaEditorSupport/julia-vscode#310]
Particularly when used as infix, it would be slick to apply some highlighting to `isa`

**Comment by ZacLN** [comment]
It already is, https://github.com/JuliaEditorSupport/julia-vscode/blob/master/syntaxes/julia.json#L276, maybe your theme?

**Comment by ssfrr** [comment]
Oh, whoops. In the default theme it doesn't show up, but it does in some (e.g. Monokai).

Thanks.
