### ISSUE TITLE
Plot pane gets stuck?

### ISSUE THREAD

**Issue by tuckermcclure** [JuliaEditorSupport/julia-vscode#314]
The plot pane seems to work for me for small, simple plots. After a few plots with a little more to them, the plot pane stops updating. I have to delete its plots and then make _two_ small plots before it's responsive again.

E.g., this usually works the first time:

```
    # Choose a plotting package.
    # pyplot() # Crashes after update on 2017-10-19.
    plotlyjs()

    # Define each plot that we'll need.
    p1 = plot(t, q_BI.',
              label  = ["q1" "q2" "q3" "q4"],
              ylabel = "Attitude Quaternion")
    p2 = plot(t, 180/π * ω_BI_B.',
              label  = ["ω1" "ω2" "ω3"],
              ylabel = "Rotation Rate (deg/s)")

    # Display those plots as subplots using the default "2" layout. Put any
    # common descriptors here.
    display(plot(p1, p2,
                 layout = 2,
                 xlabel = "Time (s)"))
```

However, when I change those variables and re-run it, it won't update the plot. If I do this:

```
plot(randn(10,10))
```

then nothing happens. If I do it _again_, then I see 10 random lines, each 10 samples long.

Now, if I re-run my plot code above, I see the plot.

I'm on Window 10, Julia 0.6, and VS Code 1.17.1, julia-vscode 0.7.0.

Anyone else seeing this issue?

**Comment by ArchieCall** [comment]
You might try upping VS Code to Version 1.17.2
This correct various terminal issues which could impact the plot pane.

Maybe you have a typo on your Version of 0.7. => if correct that dates to Aug 2015!

**Comment by tuckermcclure** [comment]
Sorry, that was v0.7 of the Julia client for VS Code. I updated the issue.

**Comment by tuckermcclure** [comment]
The problem still exists after upgrading to 1.17.2. The first time I plot the "bit plot" (above), it works. Then, whatever I plot next doesn't show up. I can wait indefinitely, select a different pane and then come back to the plot pane, click the left and right arrows, etc. The second plot won't show up. The third plot _will_ show up, and promptly. When I click through the arrows, the second plot is missing.

**Comment by davidanthoff** [comment]
@tuckermcclure What would be fantastic if you could post a file that is self-contained that I can send line-by-line to the REPL that reproduces this issue. I tried to repo it, but I got stuck because the code above for example assumes that there are some vars defined that I don't have in my session. Thanks!

**Comment by tuckermcclure** [comment]
Sure. It's coming from an HDF5 file. I can post the file and a script to plot it. Will take a few days; I'm out of the office.

**Comment by davidanthoff** [comment]
That would help a lot, thanks!

**Comment by tuckermcclure** [comment]
@davidanthoff Ok, here's some code that reliably recreates the issue on my side.

```julia
# just-plot-it.jl

using Plots

# Choose a friendly plotting package. PyPlot behaves nicely.
# pyplot() # Stopped working after a recent update.
plotlyjs()

# Make data shaped like the data that had the problem.
t      = collect(0:3600) / 60.
q_BI   = randn(4, 3601)
ω_BI_B = randn(3, 3601)

# Define each plot that we'll need.
p1 = plot(t, q_BI.',
            label  = ["q1" "q2" "q3" "q4"],
            ylabel = "Attitude Quaternion")
p2 = plot(t, 180/π * ω_BI_B.',
            label  = ["ω1" "ω2" "ω3"],
            ylabel = "Rotation Rate (deg/s)")

# Display those plots as subplots using the default "2" layout.
display(plot(p1, p2,
             layout = 2,
             xlabel = "Time (s)"))

# If we comment out the above and only display one plot, it works the right way.
# display(p1)
```

Running that like so shows the issue:

```julia
include("just-plot-it.jl")
# Go look at plot.
include("just-plot-it.jl")
# Why didn't we get a new plot? Repeating the above will never yield a new plot.
plot(randn(5,5))
# Wait, where's the plot?
plot(randn(5,5))
# Ok, this last one showed up. Note that there are now two plots, not four. Why?
```

Note that this seems to be a problem with the `layout = 2` option.

**Comment by davidanthoff** [comment]
Thanks for this excellent bug report, I think I fixed the bug. If you still see something like this in the next beta, please re-open the issue.
