### ISSUE TITLE
Indentation of continuation lines

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/julia-vscode#316]
The VS Code editor renders the following 3 lines, of which 2 are continuation of the first, without any indentation. That is, like this:
```
fcoarsetransferred = transferfield!(fcoarsetransferred, 
fensfine, regionsfine[i]["femm"].geod.fes, fcoarse,
fcoarse, fenscoarse, regionscoarse[i]["femm"].geod.fes, geometricaltolerance)
```
What I would like of course is
```
fcoarsetransferred = transferfield!(fcoarsetransferred, 
        fensfine, regionsfine[i]["femm"].geod.fes, fcoarse,
        fcoarse, fenscoarse, regionscoarse[i]["femm"].geod.fes, geometricaltolerance)
```
Has anyone else had this experience? If so, and if it isn’t just me, are there any fixes?

**Comment by PetrKryslUCSD** [comment]
I was advised to use the settings:
```
"editor.wordWrap": "on",
"editor.wrappingIndent": "indent",
```
Not sure if it's the right thing to do, but in any case nothing happened: the continuation lines are still not indented with respect to the first one.

**Comment by davidanthoff** [comment]
Should we close that? It does seem a valid concern.

**Comment by PetrKryslUCSD** [comment]
Re-installation  of VS code and the extension solved the issue with soft wrap.

**Comment by davidanthoff** [comment]
Yeah, but soft-wrap is not really a great solution, there are lots of projects that have guidelines that code should not have more than x chars per line, and for all of those this issue actually applies.

**Comment by PetrKryslUCSD** [comment]
I submitted a second issue on exactly that. Thanks.
P

Petr Krysl
Professor
University of California, San Diego
9500 Gilman Dr., #0085, La Jolla, CA 92093
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by davidanthoff** [comment]
Great, thanks! I'll close this one then.
