### ISSUE TITLE
Continued: Indentation of continuation lines

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/julia-vscode#317]
Consider the following sample code:
```
fcoarsetransferred = transferfield!(fcoarsetransferred, 
        fensfine, regionsfine[i]["femm"].geod.fes, fcoarse,
        fcoarse, fenscoarse, regionscoarse[i]["femm"].geod.fes, geometricaltolerance)
```
This is how would like the continuation lines to be indented. However, the VS Code editor when  re-indenting renders the following 3 lines, of which 2 are continuation of the first, without any indentation. That is, like this:
```
fcoarsetransferred = transferfield!(fcoarsetransferred, 
fensfine, regionsfine[i]["femm"].geod.fes, fcoarse,
fcoarse, fenscoarse, regionscoarse[i]["femm"].geod.fes, geometricaltolerance)
```
Of course, I could join all 3 lines into a single long line and then use soft wrap to render the code in the editor. However, what I'd like to do is split the line myself  and then for the editor to preserve the indentation when  redoing the indentation for the entire file upon "Reindent Lines".

**Comment by ZacLN** [comment]
The 'Reindent Lines' is unrelated to this package (i.e. it's from core vscode) so there's not much we can do here. You can try 'Format Document' which will leave that sort of indentation as is when it makes other changes but you'll have to see for yourself whether you like the outcome...

**Comment by PetrKryslUCSD** [comment]
I see, so "Reindent Lines" does not use any information about the syntax of the language?

**Comment by ZacLN** [comment]
I wouldn't think so

**Comment by PetrKryslUCSD** [comment]
"Format Document" does absolutely nothing with indentation.

**Comment by PetrKryslUCSD** [comment]
I tried to use  "Reindent Lines" on a couple of C-language files. It does an absolutely atrocious job: the indentation is totally wrong once some continuation lines  are included.
