### ISSUE TITLE
Plot commands don't work

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#318]
I think the recent refactoring of the extension code broke that. I had a quick look, and I think the whole idea of having the global state vars that control the plot stuff (like ``currentPlotIndex`` etc.) be part of ``PlotPaneDocumentContentProvider`` won't work.

**Comment by ZacLN** [comment]
I'm having a look at this tonight, I think it's my misunderstanding of the use of `this` in TS.

**Comment by ZacLN** [comment]
I still don't understand `this`, I'll leave it to you to have a go

**Comment by davidanthoff** [comment]
Fixed by #320.
