### ISSUE TITLE
Signature provider crashes

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#33]
I start writing the following in a julia file:

````julia
randn(
````
At this point the signature help appears. If I then close the paranthesis and move the cursor to the end of the line (i.e. after ``randn()``) the server crashes.

@ZacLN Could you have a look? I think the problem is somewhere in ``get_word``, but I don't understand that method well enough to fix this.

**Comment by ZacLN** [comment]
I have a fix for this, just making it work on function calls written across multiple lines

**Comment by ZacLN** [comment]
see pull request on your [signature-fix](https://github.com/davidanthoff/julia-vscode/pull/1) branch
