### ISSUE TITLE
Execute code block should move the cursor into the next code block

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#342]
For the execude code command we automatically advance the cursor to the next line when we executed a block of code. Would be nice if the execute code block also moved the cursor to the beginning of the next block, so that one can just keep hitting Ctrl+Enter to execute a file.

Making this a v0.8.0 because it seems a bit like a regression. But if too complicated, we can also move it back.

**Comment by davidanthoff** [comment]
In general, it might be easier if we used a LS command a la ``julia/getRangeOfCurrentBlockText`` instead of ``julia/getCurrentBlockText``. That command would just return the start position and the length of the code block that surrounds the position that was sent. I think that would have two benefits: a) we would ship less stuff around, b) we could use that message to also implement the cursor repositioning.

**Comment by ZacLN** [comment]
#349
