### ISSUE TITLE
Think about LS statusbar UI

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#358]
Right now we always show ``Julia Language Server`` in the status bar. If the LS is busy it turns red. In some way that seems wasteful in terms of UI space. Maybe a better idea would be to only show something while the LS is busy, and just nothing when it is ready... Other ideas also welcome.

**Comment by ZacLN** [comment]
One option I was thinking of was that we could use it to show the current module for the REPL (instead of the REPL prompt) and pop up the 'change module' command when clicked

**Comment by MFairley** [comment]
I personally don't like the red font because it stands out in the UI and is distracting. I would prefer if the font were just the regular white like the other items in the status bar.

**Comment by KristofferC** [comment]
Agreed witht he red font being a bit "loud".
