### ISSUE TITLE
Revise.jl has some issues in our REPL

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#361]
Reported on Slack by Scott Thomas, for our v0.8.0-rc.3:

> Not having any luck using Revise.jl within VS Code. Changes just don’t seem to get picked up in the REPL (maybe because of the REPL module thing?) I can manually do Revise.revise() but it would be nice to have it apply the changes immediately like in the normal REPL. Anyone else run into this?
This was on both OSX at work and Ubuntu at home. Also with Revise being loaded in juliarc.jl, which means it should in theory be loaded when the terminal starts up. I might see if anything changes if I remove it from there and run it explicitly in the terminal within VS Code.

> Ok so the problem goes away if I do that… so the default way of setting up Revise to run automatically doesn’t work with how VSC starts the terminal

````julia
@schedule begin
  sleep(0.1)
  @eval using Revise
end
````
> Increasing the delay from 0.1 to 1 makes it work

> Wrapping it in `Base.atreplinit() do REPL […] end` with the shorter delay also works

It is not clear to me what we could do about this? Maybe change [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/scripts/terminalserver/terminalserver.jl#L195) loop slightly? For example by inserting a ``sleep(0.1)`` or something like that in there? I think the current code probably will consume a 100% of the process until it succeeds. But I don't really understand the root issue here, so this is stumbling in the dark on my part ;)

I do think we need to sort this out for the v0.8.0 release, given how prominent Revise.jl is.

@timholy just CCing you as well in case you have an obvious idea what the problem might be. When we start the REPL in VS Code, it runs [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/scripts/terminalserver/terminalserver.jl) code at startup, and something in there seems to conflict with Revise.jl.

**Comment by davidanthoff** [comment]
Alright, @KristofferC pointed out that this
````julia
atreplinit() do repl
    @eval using Revise
end
````
way of starting Revise in ``.juliarc.jl`` works, but there is a question whether that would work in IJulia.

**Comment by davidanthoff** [comment]
Maybe we should just mention @KristofferC's solution in the README for now, and not make this blocking for v0.8.0?

**Comment by davidanthoff** [comment]
I just tried that workaround and it doesn't work on my Windows system...

**Comment by davidanthoff** [comment]
Moving to the backlog, we now have a workaround described in the README, that has to be good enough for now.

**Comment by timholy** [comment]
Sorry to be slow chiming in here, I was traveling and not keeping up with the flux.

Glad you found a workaround. I may poke at this a bit myself sometime, but for now I don't have any better ideas.
