### ISSUE TITLE
Writing `` end`` should auto-unindent

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#37]

**Comment by ZacLN** [comment]
[ref](https://github.com/Microsoft/vscode/issues/2272)

**Comment by davidanthoff** [comment]
There is some new info about this at Microsoft/vscode#2272. I don't fully understand it, but does this mean we can actually solve this right now?

**Comment by tkelman** [comment]
It looks like they might at least make it so hitting enter after typing the end will de indent it?

**Comment by davidanthoff** [comment]
Yeah, that is my impression. Microsoft/vscode#17868 has a lot of text, but it is still not entirely clear to me what the current status is, to be honest... But it does seem to be on the January 2017 milestone, so I assume something is going to improve with the next version.

**Comment by davidanthoff** [comment]
Just an update here: things now work when one hits enter, i.e. then the line gets properly indented. I would still much prefer that things auto unindent when the word ``end`` has been typed, but we'll have to wait for upstream support for that.

I believe the upstream issue is Microsoft/vscode#2272.

**Comment by davidanthoff** [comment]
Solved with VS Code 1.14. You need to set the ``editor.autoIndent`` user setting to ``true`` for this to work.
