### ISSUE TITLE
Eval block behaving oddly on a regex

### ISSUE THREAD

**Issue by malmaud** [JuliaEditorSupport/julia-vscode#381]
Position the cursor anywhere on this line:

```
match(r"Input \d+ \(s+\)", s)
```

then run `Execute block`.

The REPL shows this (note the position of the cursor and the newly-introduced newline) without executing the code until I push 'enter'

<img width="400" alt="screen shot 2017-11-09 at 1 00 56 pm" src="https://user-images.githubusercontent.com/987837/32621570-3420ee56-c54e-11e7-8660-4199ef241258.png">
 in the REPL.

**Comment by KristofferC** [comment]
Maybe OhMyREPL.jl fault as well?

**Comment by davidanthoff** [comment]
Yeah, seems to work fine without OhMy REPL.jl.

**Comment by malmaud** [comment]
Ah, makes sense.

**Comment by davidanthoff** [comment]
@KristofferC Is that something you can fix on OhMyREPL's side? I'll assume yes for now and close this, if we need to do anything else here please let us know.

**Comment by KristofferC** [comment]
I will look into it.
