### ISSUE TITLE
Skipping commented lines

### ISSUE THREAD

**Issue by DNF2** [JuliaEditorSupport/julia-vscode#392]
When evaluating a block, the extension ingests and spits out blocks of commented code, like so:

```
for i in 1:2
    println(i)
end

# a = 1
# b = 2
```
Output is:
```
Main> for i in 1:2
          println(i)
      end
1
2

Main> # a = 1

Main> # b = 2

Main>
```
Can or should commented-out lines be skipped?

**Comment by ZacLN** [comment]
Yes, we should use length(x.span) rather than x.fullspan

**Comment by davidanthoff** [comment]
@ZacLN This is implemented, right? If not, please reopen the issue.
