### ISSUE TITLE
What to do about @__FILE__ and @__DIR__ in code execution

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#394]

**Comment by YongHee-Kim** [comment]
Maybe overriding `@__FILE__` and `@__DIR__`  from `LanguageServer` would works? 
I've tried to override those in my module and found that I can get [path of active window](https://github.com/Tyriar/vscode-terminal-here/blob/master/src/extension.ts)

But don't know how to call typescript from Julia, so I stopped there :sweat_smile:

**Comment by ZacLN** [comment]
I think a simple reflex replace (on the table side) should do the trick here

**Comment by stakaz** [comment]
Would it be possible to look at how it is done in Atom? Each of my scripts contains `cd(@__DIR__)` as the first line to ensure it knows, where it is run. However, I cannot test the scripts from VS Code as it does return the workspace directory and not the file directory. Thanks.

**Comment by phlavenk** [comment]
I'm very supportive of @stakaz idea. At least for ctrl-enter, we could do a direct regex replacement of @__DIR__ etc. with the path of the active file. Even though there would be an inconsistency on the REPL, it's usefulness is without debate.
