### ISSUE TITLE
Latex completions do not work in comments or docstrings

### ISSUE THREAD

**Issue by joshday** [JuliaEditorSupport/julia-vscode#400]
I'm not sure about comments, but for docstrings maybe there's a conflict with `source.gfm`?

I'm on OSX julia-vscode version 0.8.0

**Comment by ZacLN** [comment]
These appear to work on my system when manually  triggered (ctrl+space is default I think)

**Comment by joshday** [comment]
Ah, that works for me.  There's no issue here, just an editor setting which turns suggestions off in comments and strings by default:

```json
  // Controls if suggestions should automatically show up while typing
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
```

**Comment by ZacLN** [comment]
ah cool, I wasn't aware. @davidanthoff, should we maybe turn this on by default?

**Comment by davidanthoff** [comment]
Yes, that sounds good, especially for latex completions. Question is, can we do that in our extension? This looks like a user setting, right?

**Comment by joshday** [comment]
Are extensions allowed to add something like this?  This is what I've added to my user settings to override the defaults. 

```
"[julia]": {
    "editor.quickSuggestions": true
  }
```

**Comment by ZacLN** [comment]
#402

**Comment by davidanthoff** [comment]
@ZacLN this is also implemented, and I can close here, right?
