### ISSUE TITLE
missing latex superscript completions

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaEditorSupport/julia-vscode#418]
After hitting just `\^` the available completions are not shown. Also, some of the completions are not available at all. 
For example, I can complete `x\^a` to `xᵃ` but I'm not able to tab-complete `x\^2` to `x²`.

**Comment by ZacLN** [comment]
Does manually triggering completions (ctrl+space) not work for you?

**Comment by CarloLucibello** [comment]
> Does manually triggering completions (ctrl+space) not work for you?

mhm, no. It does for you?

**Comment by CarloLucibello** [comment]
Bye the way, for subscripts e.g. `x₂`, completions works well

**Comment by davidanthoff** [comment]
I tried to replicate this, no luck. Yes, when I just type ``\^`` no completions appear, but if I then hit Ctrl+space, the list appears.

I'm closing this for now because I believe this is just the default VS Code behavior.
