### ISSUE TITLE
Unrecognized generator variable

### ISSUE THREAD

**Issue by cossio** [JuliaEditorSupport/julia-vscode#419]
Inside a function definition, the generator variable is not recognized if the generator contains a condition. Here is an example. In the first line, the variable is not highlighted. In the second case, when the genrator contains a condition, the variable has squiggly lines.

![image](https://user-images.githubusercontent.com/10637482/33458916-00b1410a-d620-11e7-9054-fa71a814d443.png)

**Comment by ZacLN** [comment]
this is fixed in the forthcoming lint update so I won't push a fix here

**Comment by ZacLN** [comment]
This is shifted to v0.11.0/StaticLint merge

**Comment by ZacLN** [comment]
fixed on alpha

**Comment by cossio** [comment]
@ZacLN Nice to see so many things getting closed! I can't wait to try the new vscode extension. Thanks for the hard work.
