### ISSUE TITLE
<file> is included by more than one file, following the first

### ISSUE THREAD

**Issue by staticfloat** [JuliaEditorSupport/julia-vscode#420]
Many of my projects are multiple experiments using the same codebase, e.g. I have a folder `libcough` that contains a bunch of routines that are used by top-level script files in the project root directory.  When the VSCode extension parses all the top-level scripts, it complains about each and every one, saying:

```
WARNING: file:///home/sabae/src/coughsense3/libcough/libcough.jl is included by more than one file, following the first: file:///home/sabae/src/coughsense3/playground.jl
WARNING: file:///home/sabae/src/coughsense3/libcough/libcough.jl is included by more than one file, following the first: file:///home/sabae/src/coughsense3/interval_windows.jl
WARNING: file:///home/sabae/src/coughsense3/libcough/libcough.jl is included by more than one file, following the first: file:///home/sabae/src/coughsense3/model_perf.jl
WARNING: file:///home/sabae/src/coughsense3/libcough/libcough.jl is included by more than one file, following the first: file:///home/sabae/src/coughsense3/classify_file.jl
....
```

This isn't critical, they are only warnings, but it is somewhat annoying.

**Comment by davidanthoff** [comment]
@ZacLN We should probably just not emit this warning? Not sure what a user would do with that info, right?

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/248
