### ISSUE TITLE
Weave commands not working

### ISSUE THREAD

**Issue by shorty66** [JuliaEditorSupport/julia-vscode#427]
When i try to use any weave command, the `Julia Weave` console pops up but remains empty. No files or previews are generated.

This happens with both `8.1.0` and `9.0.0-beta`.

I have the weave package installed and most weave commands (short of pandoc, as i don't use that) work from a REPL.

Did i miss any configuration or are you able to reproduce the issue?

**Comment by davidanthoff** [comment]
It should just work if you have Weave installed. BUT, I haven't tried it in a while, I'll try to take a look soon.

**Comment by davidanthoff** [comment]
This should be fixed in the next release. Thanks for reporting!
