### ISSUE TITLE
linter problem with submersed modules

### ISSUE THREAD

**Issue by phlavenk** [JuliaEditorSupport/julia-vscode#440]
```julia
#file foo.jl: 
module Foo
include("bar.jl")
end

#file bar.jl
module Bar
function f(x)= x
end
```
the whole Foo.Bar module (the whole file bar.jl) is not parsed correctly with following error:
[LanguageServer.LSDiagnostics] Parsing Failure 
Thank you
Petr

**Comment by ZacLN** [comment]
That's because it's incorrect syntax 😄, you're missing an `end` for the function declaration

**Comment by phlavenk** [comment]
Thank you,
Unfortunately I did the same mistake in both my huge project and in my attempt minimal working example. Good to know the missing end ruins the whole file.
Is there a way to quickly switch the linting on and off on demand?
