### ISSUE TITLE
unable to set julia exec path in VScode (ubuntu 16.04)

### ISSUE THREAD

**Issue by bharathgs** [JuliaEditorSupport/julia-vscode#442]
**Error: Could not start the julia language server. Make sure the configuration setting julia.executablePath points to the julia binary.**

I'm unable to set the julia exec path in my vscode settings
(I'm on ubuntu 16.04)

this is what i have on my system: 

```bash
whereis julia
julia: /usr/bin/julia /etc/julia /usr/local/bin/julia /usr/share/julia /home/xenomorph/applications/julia/julia-0.6.2/bin/julia /usr/share/man/man1/julia.1.gz
```
I tried to set these accordingly, but I always end up with the above error.

**Comment by davidanthoff** [comment]
What exactly does your configuration setting look like?

**Comment by bharathgs** [comment]
Hey, not sure what the issue was but now it seems to be working. (I did not change anything)
thanks (and I'll close this :slightly_smiling_face: )
