### ISSUE TITLE
LanguageServer doesn't reload open textDocuments on crashing

### ISSUE THREAD

**Issue by ZacLN** [JuliaEditorSupport/julia-vscode#450]
For example (😄) error on julia-vscode-debug at 12:55:34 on 1/13/2018 following unicode error.

I'm guessing no `didOpen` command is sent following a crash so we need to make an explicit request from LS -> vscode for a tuple of `(uri, context)` of `vscode.workspace.textDocuments` on each startup (at the end of the `initialized` response) and load the documents on the LS side if they're not already present

**Comment by davidanthoff** [comment]
Should we maybe ask over on the LS spec repo how we should handle that? It seems a pretty generic issue and there might be a recommended way to do this?

I would say we put this on the backlog for now, doesn't seem a super critical thing, and it would be nice to get v0.10 out.

**Comment by ZacLN** [comment]
I’m happy to get the release out but do think this is important- crashes require a restart of vscode

**Comment by davidanthoff** [comment]
Well, I was mainly thinking that if LS crashes say because of a unicode error, it will restart and crash right again, right? And try that 5 times, and then shut down, so even if we fix this, the user experience won't be much better.

But, there is of course the scenario where LS crashes because of a bug that won't appear right again in the next session, and in that case fixing this here would help.

Perfectly happy to make this part of v0.10!

**Comment by ZacLN** [comment]
No more Unicode errors!!!
Yes I see what you mean and agree- release!

**Comment by davidanthoff** [comment]
Alright, I've asked what we should do over at MS: https://github.com/Microsoft/vscode-languageserver-node/issues/304.

**Comment by davidanthoff** [comment]
Ok, just a quick update: this was a bug on the MS side of things, now fixed. When the LS crashes, it will send the correct ``didOpen`` requests right after startup. I'm still waiting for some feedback how we can get that bugfix, but this should stop us much longer.

**Comment by Roger-luo** [comment]
Am I suffering this bug? I'm using Ubuntu 16.04 with Julia v0.6

```
[Error - 2:27:31 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/roger/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose 
```

**Comment by davidanthoff** [comment]
@Roger-luo This bug is only a follow up bug if the language server already crashed due to something else, so I don't think this would explain the root problem.

**Comment by davidanthoff** [comment]
Alright, we have a fix upstream and I just pushed an update to ``master`` that uses it. I'm closing for now.
