### ISSUE TITLE
Issue with KeyError: key LanguageServer.URI2(...) not found

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#453]
Application version: 0.10.0-dev
Cloud role name: Extension
Device type: PC
Event time: 1/21/2018, 5:56:11 AM
Exception type: KeyError
extversion: 0.10.0-dev
Failed method: getindex
Operating system: Windows_NT 10.0.16299
Problem Id: KeyError at getindex
Sample Rate: 100
SDK version: node:1.0.1
Severity level: Error
Telemetry type: exception
vscodeversion: 1.19.2

<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&componentName=julia-vscode-dev&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%2522dff049f1-feb2-11e7-8867-95594c7262fb%2522%252C%2522name%2522%253A%2522KeyError%253A%2520key%2520LanguageServer.URI2(%2526%252334%253Bfile%253A%252F%252F%252Fc%25253A%252FUsers%252Fmatth%252FOneDrive%252FJulia%252FRWData.jmd%2526%252334%253B)%2520not%2520found%2522%252C%2522eventTime%2522%253A%25222018-01-21T13%253A56%253A11.067Z%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522Name%2522%253A%2522julia-vscode-dev%2522%252C%2522SubscriptionId%2522%253A%25226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%2522%252C%2522ResourceGroup%2522%253A%2522Default%2522%257D%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A86400000%252C%2522createdTime%2522%253A%2522Sun%2520Jan%252021%25202018%252012%253A22%253A20%2520GMT-0800%2520(Pacific%2520Standard%2520Time)%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%257D%257D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&resourceName=julia-vscode-dev&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522KeyError%2520at%2520getindex%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222018-01-22T01%253A56%253A11.067Z%2522%252C%2522createdTime%2522%253A%25222018-01-21T20%253A22%253A26.126Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D" target="_blank">View similar exceptions in this time range<\a>

**Comment by ZacLN** [comment]
This is #450

**Comment by davidanthoff** [comment]
Ok, then we should probably try to fix #450 for v0.10, right? I'll close this one here.
