### ISSUE TITLE
Issue with Failed to precompile LanguageServer to C:\Users\XXX\.vscode\extensions\julialang.language-julia-0.10.0-beta.2\scripts\languageserver\julia_pkgdir\lib\v0.7\LanguageServer.ji.

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#456]
Application version: 0.10.0-beta.2
Cloud role name: Extension
Device type: PC
Event time: 1/25/2018, 12:39:18 AM
Exception type: ErrorException
extversion: 0.10.0-beta.2
Failed method: error
Operating system: Windows_NT 10.0.16299
Problem Id: ErrorException at error
Sample Rate: 100
SDK version: node:1.0.1
Severity level: Error
Telemetry type: exception
vscodeversion: 1.19.2

<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&componentName=julia-vscode-dev&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%2522451ffdc1-01ab-11e8-929c-e9efb583bee8%2522%252C%2522name%2522%253A%2522Failed%2520to%2520precompile%2520LanguageServer%2520to%2520C%253A%255C%255CUsers%255C%255CCVO%255C%255C.vscode%255C%255Cextensions%255C%255Cjulialang.language-julia-0.10.0-beta.2%255C%255Cscripts%255C%255Clanguageserver%255C%255Cjulia_pkgdir%255C%255Clib%255C%255Cv0.7%255C%255CLanguageServer.ji.%2522%252C%2522eventTime%2522%253A%25222018-01-25T08%253A39%253A18.065Z%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522Name%2522%253A%2522julia-vscode-dev%2522%252C%2522SubscriptionId%2522%253A%25226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%2522%252C%2522ResourceGroup%2522%253A%2522Default%2522%257D%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A86400000%252C%2522createdTime%2522%253A%2522Thu%2520Jan%252025%25202018%252021%253A37%253A54%2520GMT-0800%2520(Pacific%2520Standard%2520Time)%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522ErrorException%2520at%2520error%2522%255D%257D%257D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&resourceName=julia-vscode-dev&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522ErrorException%2520at%2520error%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222018-01-25T20%253A39%253A18.065Z%2522%252C%2522createdTime%2522%253A%25222018-01-26T05%253A39%253A13.936Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D" target="_blank">View similar exceptions in this time range<\a>

**Comment by davidanthoff** [comment]
Ah, wait, this is with julia 0.7, which we don't support, so we can ignore.

**Comment by ZacLN** [comment]
Should we check for that?
