### ISSUE TITLE
Cannot get julia.executablePath to work in Windows 10 (latest version of Julia and W10)

### ISSUE THREAD

**Issue by Arie-vw** [JuliaEditorSupport/julia-vscode#459]
I have this setting:
   "julia.executablePath": "E:/Programs/julia/bin"
because strings seem to have \ for escape and \\\\ also did not work.

The exe is really there:
   E:\Programs\julia\bin>dir *.exe
  16-12-2017  15:29           512.070 julia.exe

Also the excutable is present in the PATH env variable:
   >set path
    Path=C:\Program Files (x86)\Intel\iCLS Client\;  . . . ; E:\Programs\julia\bin; . . .

Any ideas?

**Comment by ZacLN** [comment]
Hi, 1) are you on the current release of Julia-vscode or the current beta? 2) by latest Julia do you mean 0.6.2 or 0.7DEV ?

**Comment by Arie-vw** [comment]
Hi, it is the stable version 0.6.2.

2018-01-27 16:50 GMT+01:00 ZacNugent <notifications@github.com>:

**Comment by Arie-vw** [comment]
Hi David, I could fix it, but I am still not sure about what I really did.
Since in the past I got bitten a few times by unprintable characters, I did the following:
1. used your example
2. copied my path
3. replaced your path in mine
4. fed that to VScode settings
and hurray it works.
Still seems like magic ...

Many thanks for the help anyway.

**Comment by davidanthoff** [comment]
The next release will automatically find Julia if it is installed in the default location that the installer suggests, so hopefully this will become a zero config story for many folks. But your case is different of course because you installed Julia in a different location.

**Comment by Arie-vw** [comment]
OK. Nice to know.
Thx!

Op za 27 jan. 2018 19:04 schreef David Anthoff <notifications@github.com>:
