### ISSUE TITLE
cannot view plot in julia Plot Pane

### ISSUE THREAD

**Issue by lsalo** [JuliaEditorSupport/julia-vscode#460]
Hi,
I recently installed the julia extension (version 0.9.1) in Ubuntu 16.04, and I cannot view plots after running the code. I have tested the following code (see picture). From the output console it seems that the code is running fine. 

![screenshot from 2018-01-28 12-50-11](https://user-images.githubusercontent.com/35502293/35485189-d95c74f2-0429-11e8-9b98-77090e641399.png)

I am new to vs code so maybe I am doing something wrong? Anyone experienced the same issue? 

Thanks,
Lluis

**Comment by davidanthoff** [comment]
Hm, that works for me. How are you running the code? I'm slightly confused that you seem to have output in the OUTPUT tab in the lower half, whereas the code really should be run in the TERMINAL tab at the REPL?

**Comment by ZacLN** [comment]
I think this is from running the file

**Comment by davidanthoff** [comment]
But even F5 doesn't send anything to OUTPUT, right? And the dropdown shows `Code`, which I'm also not clear about.

**Comment by lsalo** [comment]
Thanks for the replies, @davidanthoff and @ZacLN 
As you said, when I run it in debug mode (f5) I can view the plot in the Plot Pane, and it doesn't send anything to output. The commands are sent to terminal, dropdown julia. However, when I run it as "Run Code" (ctrl + alt + n) then I cannot view the plot, and I do not understand why. Should I always run with f5? On the other hand, ctrl + alt + n always brings me to output.

**Comment by RandomString123** [comment]
Is "Run Code" from an extension you installed?  My vscode which is very vanilla does not have it.

**Comment by lsalo** [comment]
Hey @RandomString123. Yes, I think that may be key - I was trying to use the "code runner" extension, which does not have support for julia as far as I know.

**Comment by davidanthoff** [comment]
Yes, that  command seems to be from a different extension. I’ll close this issue because it really doesn’t have anything to do with this repo here.
