### ISSUE TITLE
Strange Cut and Paste Behavior

### ISSUE THREAD

**Issue by RandomString123** [JuliaEditorSupport/julia-vscode#462]
At first I thought I was seeing this but my case is slightly different.  https://github.com/JuliaEditorSupport/julia-vscode/issues/317

If you put this code into a Julia file
```julia
function Test(param1:Any
              param2: Any
              Param3:Any)
    printf("Happy Stuff")
end
````
And then copy and paste it into another file vscode mushes everything to the left.  Notice the printf line now has no indentation and the  params moved left one. 
```julia
function Test(param1:Any
    param2: Any
    Param3:Any)
printf("Happy Stuff")
end
```

However if you copy and paste the code below which is formatted as vscode wants to format it by default, then the code remains unchanged after the paste.
```julia
function Test(param1:Any
    param2: Any
    Param3:Any)
    printf("Happy Stuff")
end
````

**Comment by davidanthoff** [comment]
@ZacLN is this even us, or just VS Code behavior?

**Comment by ZacLN** [comment]
Yep this is out of our control

**Comment by RandomString123** [comment]
I will file something with the vscode folks.  It is not a huge deal to reformat code, but it is strange that cut and paste would destroy existing formatting.

**Comment by RandomString123** [comment]
Created an issue, got told to turn autoIndent off.  But never heard back about why it is formatting code so poorly.   Anyway not a Julia thing so closing this issue.

https://github.com/Microsoft/vscode/issues/42543
