### ISSUE TITLE
go-to-definition got the wrong definition

### ISSUE THREAD

**Issue by kindlychung** [JuliaEditorSupport/julia-vscode#464]
Here are the screenshots:

![screenshot from 2018-02-04 16-36-10](https://user-images.githubusercontent.com/995761/35779223-bfec846c-09c9-11e8-87d9-d7ed0faeb5c3.png)
![screenshot from 2018-02-04 16-36-21](https://user-images.githubusercontent.com/995761/35779224-c419ecbe-09c9-11e8-8e39-11bbe80bc43a.png)

The `string` method here has nothing to do with git hash.

**Comment by KristofferC** [comment]
Without running the code it is very hard (some times impossible) to know what string method you will dispatch to. That is why you get the list to the right presumably.

**Comment by davidanthoff** [comment]
Yeah, it might be any of the definitions to the right. I don't think there is anything we can do about this... Unless @ZacLN has some idea. I'm closing for now.
