### ISSUE TITLE
Git bash terminal does not open in a pane

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/julia-vscode#465]
I set Shell to C:\Program Files\Git\git-bash.exe . The terminal opens in an outside window, not inside the editor.

**Comment by KristofferC** [comment]
Did you mean to open this in the Juno repo? (ref https://discourse.julialang.org/t/ann-juno-0-6-7/8622/67)

**Comment by PetrKryslUCSD** [comment]
Sorry, wrong "issues".
