### ISSUE TITLE
Support Run Cell feature

### ISSUE THREAD

**Issue by findmyway** [JuliaEditorSupport/julia-vscode#466]
Currently julia-vscode support the following short-cuts:

> - Ctrl+Enter: if no code is selected, run the current line in the REPL and advance the cursor to the next line. If code is selected, run the selection in the REPL.
> - Alt+Enter: run the code block that encloses the current cursor position in the REPL and advance the cursor to the next code block.
> - F5: run the content of the current file in the REPL.
> https://github.com/JuliaEditorSupport/julia-vscode/wiki/Keyboard-shortcuts

When doing experiments within julia-vscode, several lines are organized as a logical unit and I usually have to 

1. select those lines
2. Ctrl + Enter, send them to repl
3. edit several places
4. select those lines AGAIN! 

It would be great to have another short-cut(or button) which supports a **Run Cell** feature like the discussion here: https://github.com/DonJayamanne/vscodeJupyter/issues/81

**Comment by RandomString123** [comment]
This is an off the wall question, you can put a begin ... end block anywhere in Julia code.  Is there a reason you wouldn't just put in a begin...end and then just use Alt-Enter?  

I think an easy solution to this would be to modify the syntax to indicate that #%% should create a code block.

**Comment by findmyway** [comment]
@RandomString123 
Ah, thanks for your reminder.

I think `begin ... end` and the empty `let ... end` blocks are enough to do the things I want.
I'm just not accustomed to that style at the first.
So I'll close this issue.

**Comment by davidanthoff** [comment]
Actually, I think we should support something like this with a less intrusive syntax, so I'm reopening and putting it on the backlog.

**Comment by davidanthoff** [comment]
Closing this again because we already have an issue for this: #560.
