### ISSUE TITLE
Could not start the julia language server

### ISSUE THREAD

**Issue by Roger-luo** [JuliaEditorSupport/julia-vscode#468]
My VS code cannot find the executable even I specific the path.

User settings:
```json
{
    "window.zoomLevel": 4,
    "editor.fontFamily": "'monaco', 'WenQuanYi Micro Hei'",
    "editor.fontSize": 15,
    "sublimeTextKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "editor.formatOnPaste": true,
    "python.venvPath": "~/miniconda/envs",
    "python.pythonPath": "/home/roger/miniconda3/envs/novel/bin/python",
    "julia.executablePath": "/home/roger/julia/bin/julia",
    "[cmake]": {
        "editor.tabSize": 2
    },
    "[c]": {
        "editor.tabSize": 2
    },
    "[cpp]": {
        "editor.tabSize": 2
    }
}
```

The system is on Ubuntu16.04 with vscode version `1.18.1`, the problem is similar to #405, but it just don't work with this abspath. I also tried

`~/julia/bin/julia`
`home/roger/julia/bin`
`~/julia/bin/`
`julia`

they don't work.

**Comment by Roger-luo** [comment]
This is really weird, when I tried to dig into the source code of this extension in `out/settings.js` and print the log of section. `/home/roger/julia/bin/julia` works!

**Comment by LaszloHars** [comment]
In the Julia REPL console, I added the JSON package. After starting VS Code I edited the julia.executablePath to C:/t/Julia/bin/julia.exe (for my case) - yes, with forward slashes even in Windows. There was no more error "Could not start the julia language server".
