### ISSUE TITLE
Renaming a variable (F2) doesn't always work

### ISSUE THREAD

**Issue by rjplevin** [JuliaEditorSupport/julia-vscode#472]
Rename a variable (F2) sometimes does nothing if I use keyboard commands to select the text. It seems to work reliably, however, if I double-click on the name.

**Comment by davidanthoff** [comment]
Moving this to the backlog. Mainly we are trying to get a release out right now that works on 1.0, we'll revisit this in the next release.

**Comment by mahdizakizadeh** [comment]
Renaming with `F2` specifically does not work when I want to change a function argument name

**Comment by ZacLN** [comment]
Could you provide a minimal example? (i.e. an function and position of cursor when you try to rename) 
Thanks

**Comment by mahdizakizadeh** [comment]
It's now working, I don't know exactly why it didn't worked last time...
Thanks

**Comment by davidanthoff** [comment]
@rjplevin do you still have that problem with v0.11.5? If not, I'd close this issue.

**Comment by rjplevin** [comment]
I just did a couple of quick tests, but it works.

**Comment by davidanthoff** [comment]
Ok, I'll close it for now, if it shows up again, please reopen!
