### ISSUE TITLE
String Literal raw"..." causes Parsing Failure when '\' is used.

### ISSUE THREAD

**Issue by dariens** [JuliaEditorSupport/julia-vscode#480]
include(raw"C:\Users\") is acceptable, but will cause a Parsing Failure in VS Code.

**Comment by KristofferC** [comment]
I only get a "could not include" warning, not a full parsing failure.

**Comment by dariens** [comment]
Looks like my editor was just stuck. Same for me after restarting my portable version of VS Code. Sorry about that.
