### ISSUE TITLE
include does not take context as the directory the file is in

### ISSUE THREAD

**Issue by phrmoy** [JuliaEditorSupport/julia-vscode#481]
Hi there,

As per the documentation:

"include(path::AbstractString)
Evaluate the contents of the input source file in the current context. Returns the result of the last evaluated expression of the input file. During including, a task-local include path is set to the directory containing the file. Nested calls to include will search relative to that path. All paths refer to files on node 1 when running in parallel, and files will be fetched from node 1. This function is typically used to load source interactively, or to combine files in packages that are broken into multiple source files."

Now, in VS Code, for sources file deeper in the directory tree, it seems I need to do ```include(./dir0/.../source.jl)``` where ```./``` is the project's directory, not the file's as specified above. I am having issues with this since I don't seem to be able to run ```julia``` from the command line given that the behaviour of ```include``` seems changed.

For instance, if I am on ```./dir0/dir1/source1.jl``` and I want to include a source file a directory above, in VS Code I would specify the entire path ```./dir0/source0.jl```, in Julia, it only works if I take into account the corrent context, the directory of the file calling ```include```, in that case, I would call ```include("../source0.jl")```

```include(./dir0/source0.jl)``` this works on VS code, but not when running ```julia```
```include("../source0.jl")``` this works when running ```julia```, but not on VS Code.

Please advise, thank you.

**Comment by davidanthoff** [comment]
Yes, that is an issue we have when you run code in the REPL. I have some ideas how we can fix this, but it will probably take a while to get to that, I'm afraid.

**Comment by phrmoy** [comment]
Thanks for the reply. So is it fair to say that at the moment we should ignore REPL development within VS Code until this is sorted out or is there a current workaround such I still get to run my Julia code from the command line evoking ```julia source.jl```?

**Comment by davidanthoff** [comment]
You can make the directory where the file is located the current directory using ``cd(path)``. Any ``include`` in a file that you are including should work just fine.

**Comment by phrmoy** [comment]
I see but that is probably not a feasible workaround for a complex source tree, which is my case. I liked the VS Code extension quite a lot, looking forward to getting that interactivity back which is one of the selling points of using Julia. Thanks for your work.
