### ISSUE TITLE
Feature request: support TODO etc. highlight

### ISSUE THREAD

**Issue by Roger-luo** [JuliaEditorSupport/julia-vscode#484]
It would be very convenient if the extension itself could support highlight for 

```
# TODO: 
# FIXME:
# NOTE:
``` 

just like the Python extension in vscode

Bests,
Rgoer

**Comment by jitixi** [comment]
I think you need this https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

**Comment by Roger-luo** [comment]
I see, thank you @jitixi
