### ISSUE TITLE
Don't start LS on julia 0.7

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#491]
Right now we are getting lots of crash reports on that scenario, really unnecessary, given that we know it doesn't work.

**Comment by rapus95** [comment]
I guess this should be sort of reconsidered/reopened since the beta has been released and people have been encouraged to try out the new version.

**Comment by davidanthoff** [comment]
Well, we know that it doesn't work on 0.7 at the moment :) I believe @ZacLN is working hard to migrate the underlying packages, and once that is done we can move forward with this.
