### ISSUE TITLE
Stop sending more commands to REPL if an error is thrown

### ISSUE THREAD

**Issue by jmboehm** [JuliaEditorSupport/julia-vscode#496]
It would be great to have the option that commands such as Ctrl+Enter ignore subsequent lines of code once an unhandled error is thrown. Sometimes it's hard to see whether one of the first lines of code were executed successfully when you send code to the REPL that produces a lot of output.

**Comment by davidanthoff** [comment]
Yeah, I agree. I've actually started to redesign that whole code execution aspect, and this would be solved by the new design.
