### ISSUE TITLE
Terminal prompt messed up after shell mode

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/julia-vscode#500]
When I use a command in the terminal that produces output, the Julia prompt becomes garbled:
![image](https://user-images.githubusercontent.com/9855832/40882400-a0ed9df2-6695-11e8-9b13-fa367aa33385.png)
I don't seem able to manage return to sanity in the prompt, and this persists until I restart Julia.
My terminal is git bash (not that I have any idea whether or not that piece of information matters).

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/26894

**Comment by ZacLN** [comment]
Seems to have been fixed upstream
