### ISSUE TITLE
Correct identation in `@testset "name" begin ... end` blocks

### ISSUE THREAD

**Issue by cossio** [JuliaEditorSupport/julia-vscode#505]
I think the correct identation should be

![image](https://user-images.githubusercontent.com/10637482/41112108-4fa53418-6a7e-11e8-8d1d-ce8d87405cd5.png)

Currently when you try to do this in VS Code, it messes the indentation. For example, if you begin typing `@testset "some test name" begin` and hit enter, the next line will not be indented. It would be nice if it were indented, and if further the `end` was automatically placed.

Copy and paste are also messed up. If you copy a `@testset` and paste it, it will have very bad identation.

**Comment by ZacLN** [comment]
There is an existing snippet for `begin` blocks and running `Format Document` should indent this properly.
