### ISSUE TITLE
Feature Request: <shift-enter> sends to REPL without output

### ISSUE THREAD

**Issue by jlperla** [JuliaEditorSupport/julia-vscode#506]
One of the nice things about Juno is that you can `shift-enter` to execute a block or line of code, and it will not necessarily output to the embedded REPL.  This removes clutter during development.  The fact that it displays the output inline is nice, but often more trouble than it is worth:

A thought:  If you use `<shift-enter>` instead of the usual `<control-enter>` Is there any way to send it to the REPL without output?  For example, if at the end of an expression it could add a `;` to make it run the code without the output?

Down the road, this could display the results inline like Atom (which must be possible since `gitlens` does it)or perhaps in a separate window if that is preferred...

**Comment by davidanthoff** [comment]
I'm currently reworking the whole code execution story. Once that is done we can take another look at the keyboard shortcuts.

**Comment by jlperla** [comment]
Sounds good.  While you are reworking the code execution, consider whether it is possible to put in the infrastructure to get something visual on executed lines.  https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens seems to do it and not mess-up performance.

**Comment by davidanthoff** [comment]
The things you can add with that API are very limited, so I don't think that will cut it for us...
