### ISSUE TITLE
could not read package directory if .juliarc.jl script contains print function.

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaEditorSupport/julia-vscode#507]
If  `.juliarc.jl` file contains `print` like this
``` julia
println("Hello world!")
# do something...
```
Then if I try to open package directory at command palette, `Error:could not read package directory` pops up.
![image](https://user-images.githubusercontent.com/7087745/41216791-c394831e-6d90-11e8-8d2a-e503c7b96b40.png)

To see what happens at `...\julialang.language-julia-0.10.2\out\openpackagedirectory.js`
I've added debug print at L27 
``` javascript
27            var juliaVersionHomeDir = yield packagepath.getPkgPath();
28            vscode.window.showInformationMessage(juliaVersionHomeDir)
```

and it seems package directory is corrupted with print function from `.juliarc.jl`
![image](https://user-images.githubusercontent.com/7087745/41216987-72206790-6d91-11e8-8be1-410cd8c4db92.png)

**Comment by davidanthoff** [comment]
That is a bug, thanks for reporting. The fix is pretty simple: we need to add a command line flag [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/604479905331b1e9333674d999b842f8828ee614/src/packagepath.ts#L16) to not run the startup script.
