### ISSUE TITLE
Connect to external process for vscode

### ISSUE THREAD

**Issue by mallochio** [JuliaEditorSupport/julia-vscode#509]
VScode is currently missing functionality to work with Julia installed on remote servers. JuliaPro/Juno currently does this through port forwarding and connecting to an external process (http://docs.junolab.org/latest/man/faq.html#Connecting-to-an-external-julia-session-on-a-remote-machine-1). Something similar would be a great addition to vscode. Thanks!

**Comment by davidanthoff** [comment]
I assume https://code.visualstudio.com/blogs/2019/05/02/remote-development will cover this scenario, and probably more comprehensively than anything we could build.

Would be great if someone could try this with the VS Code Insider build and report back whether it works!

**Comment by vchuravy** [comment]
It works great! I have been using it extensively over the last few days

**Comment by davidanthoff** [comment]
Alright, then I'll close this issue :)
