### ISSUE TITLE
[Enhancement] Take code blocks/structure into account on execution

### ISSUE THREAD

**Issue by rapus95** [JuliaEditorSupport/julia-vscode#511]
When executing the first line of code of a function definition only that gets copied to REPL. Thus if i instead ctrl+enter the last line (being an `end`) I get an error.
One could consider automatically sending the whole block (beginning with a keyword and finished by the corresponding end) to the REPL.

3 Possibilities to resolve this:
a) Don't change it
b) Always send the whole block (module, function, macro, begin, quote, for in global space)
c) send the corresponding whole block if cursor is in the line of an end or of an block opening keyword

**Comment by davidanthoff** [comment]
Try Alt+Enter in a code block

**Comment by KristofferC** [comment]
I argued the same in https://github.com/JuliaEditorSupport/julia-vscode/pull/373#issuecomment-342931954

**Comment by rapus95** [comment]
oh indeed. In that case, it seems that's something people will continue to run into :D
I've searched in the issues for this "bug". All future users will at least find this one. Who would look into PRs? :D

**Comment by davidanthoff** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/wiki/Keyboard-shortcuts

I think we should revisit the keyboard shortcuts at a later point. I'm planning to add some more code execution modes, and I think it makes more sense to revisit this when that is ready and done.

We also should think about a more discoverable documentation story...
