### ISSUE TITLE
Possible use of undeclared variable

### ISSUE THREAD

**Issue by cossio** [JuliaEditorSupport/julia-vscode#512]
This is correct Julia syntax. Here `P` is an array that has been declared before, while `Z` is a new variable.

![image](https://user-images.githubusercontent.com/10637482/41378497-8155e328-6f5f-11e8-840c-e8583799889a.png)

It should not be highlighted as error

**Comment by ZacLN** [comment]
fixed in alpha -> https://github.com/ZacLN/julia-vscode/releases/tag/j1.0alpha3
