### ISSUE TITLE
Can not install Julia REPL

### ISSUE THREAD

**Issue by SaeedMardani** [JuliaEditorSupport/julia-vscode#513]
Hi

I am tying to install Julia on VS Code in windows. I added following line to "user settings" and "work space settings" but I can not get the REPL on VS code, I also restarted the software for several times and nothing happens:
user settings:
{
  "git.ignoreMissingGitWarning": true,
    "git.autofetch": true,
    
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,

      // Points to the julia executable.
    "julia.executablePath": "C:\\Users\\zeedo\\AppData\\Local\\Julia-0.6.3\\bin\\julia.exe",
    "julia.enableTelemetry": true,
    
}
workspace settings:
{
    // Points to the julia executable.
    "julia.executablePath": "C:\\Users\\zeedo\\AppData\\Local\\Julia-0.6.3\\bin\\julia.exe",
}

Any idea what might be the problem?

**Comment by davidanthoff** [comment]
You need to use ``\\`` in JSON to enter one ``\`` (you need to escape the backslash).

But I think this should work if you just entirely remove all ``julia.executablePath`` settings, both from the user and workspace settings. VS Code should find the julia.exe automatically, given that you have it installed in the default location.

**Comment by SaeedMardani** [comment]
Hi

I finally did not came to a solution, I totally removed and reinstalled VS Code and finally it worked. :) Thanks for your time @davidanthoff.

**Comment by davidanthoff** [comment]
Glad to hear it is working now!
