### ISSUE TITLE
focus of editor not following the cursor when alt+enter

### ISSUE THREAD

**Issue by rapus95** [JuliaEditorSupport/julia-vscode#519]
It's annoying to have to alt+enter -> scroll -> alt+enter -> scroll etc
maybe you can make the window keep the focus on the cursor

**Comment by bdeonovic** [comment]
This has nothing to do with julia, but purely a vscode thing. Looks like there are even extensions to address it: https://stackoverflow.com/questions/41082702/how-to-center-the-editor-window-back-on-the-cursor-in-vscode?rq=1

**Comment by ZacLN** [comment]
Fixed https://github.com/ZacLN/julia-vscode/commit/92ed90f3100b0f9e7eb8b31f06b7c74b5fb7ee93, merge pending
