### ISSUE TITLE
Feature request: select current block

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaEditorSupport/julia-vscode#524]
I really love the Alt+Enter behaviour which understands the block structure of the code. I often want to have a block of code selected so that I can move them around or copy to other REPL/editors. Can we extend the Alt+Enter and add another key-binding that simply select the current block?

**Comment by ZacLN** [comment]
Feature added https://github.com/ZacLN/julia-vscode/commit/e5d3bd3f825c8827cbb3c0d329b340f4f5c67f47, merge pending
