### ISSUE TITLE
"Couldn't start julia language server..." inadequate popup. 

### ISSUE THREAD

**Issue by xanfus** [JuliaEditorSupport/julia-vscode#525]
Issue Type: <b>Bug</b>

I receive erroneous message about "code" not being able to start julia language server despite running REPL of julia v0.7.

Extension version: 0.10.2
VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.4.0-130-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.55GB (1.54GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by davidanthoff** [comment]
We don't currently support julia 0.7. The next release of the extension will support 0.7.
