### ISSUE TITLE
`using VegaLite` in juliarc.jl crashes julia on startup

### ISSUE THREAD

**Issue by jordancluts** [JuliaEditorSupport/julia-vscode#528]
when `using VegaLite` is in the julia startup file julia crashes on startup in vscode. `using VegaLite` works normally at the terminal in vscode and using VegaLite causes no problems when julia is launched directly.

vscode pops up a "The terminal process terminated with exit code:1"

**Comment by davidanthoff** [comment]
What version of VegaLite.jl do you have on your system?

**Comment by jordancluts** [comment]
VegaLite is version 0.3.3 and Julia is version 0.6.4

**Comment by davidanthoff** [comment]
Alright, fund the issue. You'll just have to wait until https://github.com/rofinn/FilePathsBase.jl/pull/5 gets merged and a new version tagged.

**Comment by rofinn** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16073

**Comment by ZacLN** [comment]
I assume this is resolved
