### ISSUE TITLE
Not recognizing Julia path (Windows 10, Julia v0.7 & v0.6, VS Code 1.25.1, Julia 0.10.2)

### ISSUE THREAD

**Issue by arnavs** [JuliaEditorSupport/julia-vscode#531]
What it says on the tin. I've tried all variations of `"c:/Users/Arnav Sood/AppData/Local/Julia-0.6.4/bin/julia.exe"`, which works just fine when I paste it (with quotes) straight into the shell (DOS or git bash). Also no luck when I try to wrap it in escaped quotes, i.e. `"\"c:/Users/Arnav Sood/AppData/Local/Julia-0.6.4/bin/julia.exe\""`

**Comment by davidanthoff** [comment]
It should just find the Julia binary automatically in that location, have you tried removing that setting completely?

Note also that things do not yet work with Julia 0.7

**Comment by davidanthoff** [comment]
I'm closing this for now because I think this should just work. If not, please reopen.
