### ISSUE TITLE
Weave should run in current files directory

### ISSUE THREAD

**Issue by tlnagy** [JuliaEditorSupport/julia-vscode#532]
Love the extension! I was trying it and I didn't see how I can change the directory that Weave is run in. AFAICT, Weave is always run from my home directory on Linux so all my relative paths fail in my Julia markdown file. 

- Is there any reason that the default isn't to run it in the current files directory? 
- Failing that, there should be a way to set this in the settings.

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/pull/548

**Comment by tlnagy** [comment]
Thanks!
