### ISSUE TITLE
Possible use of undeclared variable in function qualified by module

### ISSUE THREAD

**Issue by phlavenk** [JuliaEditorSupport/julia-vscode#533]
MWE:
```julia
using Unitful
foo(x::Unitful.Time) = x
const QAxis{Name, Dim} = Axis{Name, AX} where AX <: AbstractArray{Q} where Q <: Dim
const TimeAxis = QAxis{S, Unitful.Time} where S <:Any
```
where **Unitful** token of Unitful.Time is everywhere marked as "Possible use of undeclared variable"
Moreover, `S` in the ` QAxis{S, Unitful.Time}` is also marked as "Possible use of undeclared variable".

**Comment by ZacLN** [comment]
Original issue was fixed on master. There was a missing typealias parameter issue that is fixed by https://github.com/ZacLN/StaticLint.jl/commit/da37fad54dd5d329e87cf5d9b45323a25ae7acad

**Comment by phlavenk** [comment]
Thank you for fixing this.
