### ISSUE TITLE
Cannot show math bold font characters in REPL

### ISSUE THREAD

**Issue by crlaugh** [JuliaEditorSupport/julia-vscode#536]
I tried using \mbfL or \mbfTheta (or alternately \bfL and \bfTheta) at the REPL using VSCode in Julia 0.6.4 in Windows 10, but neither of these prints the correct character and instead prints a (very handsome) question mark in a box.  The normal editor shows these characters just fine, but the REPL mangles them.  I have tried changing the font in the terminal to DejaVu Sans Mono, but that did not improve the performance.  

This problem is also replicated when running Julia in a standalone console in Windows.  This problem seems to be limited to Windows - if I start Julia from a Linux terminal in Ubuntu, it prints these Unicode characters without a problem.

**Comment by davidanthoff** [comment]
This is essentially an upstream problem, I'm afraid...

**Comment by crlaugh** [comment]
Bummer.  Thanks for the info.
