### ISSUE TITLE
use softscope in terminal?

### ISSUE THREAD

**Issue by stevengj** [JuliaEditorSupport/julia-vscode#540]
Similar to JuliaLang/IJulia.jl#720, it might be worth evaluating user code with the `softscope` transformation from the [SoftGlobalScope package](https://github.com/stevengj/SoftGlobalScope.jl), to ease interactive use as discussed in JuliaLang/julia#28789.

**Comment by ZacLN** [comment]
This is being addressed by the julia devs

**Comment by stevengj** [comment]
So far there is not much progress towards this being addressed in Julia itself; you might want to reconsider using SoftGlobalScope as a stopgap.
