### ISSUE TITLE
'Run Test Task' command doesn't work with j1.0alpha3 release

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#551]
From https://github.com/JuliaEditorSupport/julia-vscode/issues/537#issuecomment-428217658. The 'Run Test Task' command probably still needs to be updated, it fails with

```julia
ERROR: UndefVarError: Pkg not defined
```

**Comment by ZacLN** [comment]
Was fixed by https://github.com/JuliaEditorSupport/julia-vscode/commit/7b14c74ab85c0f5e212ae5bca4b9b851128025b7  (I believe)

**Comment by davidanthoff** [comment]
Yeah, I was able to run tests...

**Comment by ZacLN** [comment]
That commit was made after the alpha3 tag
