### ISSUE TITLE
The formatter nows indents module body?

### ISSUE THREAD

**Issue by x-ji** [JuliaEditorSupport/julia-vscode#556]
The [documentation](https://docs.julialang.org/en/v1/manual/modules/) states that

> the style is not to indent the body of the module, since that would typically lead to whole files being indented.

and it seemed to be the case with earlier versions of the plugin. However, with alpha 3 and Julia 1.01, it seems that the module body is being indented automatically?

Test file:

```
module A
a = 1
end
```

becomes

```
module A
    a = 1
end
```

after saving.

**Comment by ZacLN** [comment]
fix: https://github.com/ZacLN/DocumentFormat.jl/commit/b10507d01e24a780fe0aaef0f7874ebb6096ffe0
thanks
