### ISSUE TITLE
LaTeX completions no longer working on alpha?

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#558]
Typing `\alpha <tab>` no longer produces α for me on OSX or Linux with alpha 4.

**Comment by ZacLN** [comment]
They should do:
1. Do they appear up in the completions list?
2. What comes up in the LanguageServer log when you `Trigger suggest` at the end of `\alp`? (we're interested in the message that follows one marked with `"method":"textDocument/completion"`
3. Are you trying this within a String?

**Comment by tkoolen** [comment]
I found out that it _does_ work once the file I'm editing is parsed. And on the machine where I encountered this issue I had issues with the Julia executable path again (not sure why, haven't had time to debug properly), so it never succeeded in parsing the file. I think this used to work also before parsing / without the language server running; did that change?

**Comment by ZacLN** [comment]
Ah ok, that explains it. The completions have relied on the language server being up and running for a while now
