### ISSUE TITLE
Can't find Julia binary on Ubuntu 18.04

### ISSUE THREAD

**Issue by onetonfoot** [JuliaEditorSupport/julia-vscode#561]
After install the extension it prompts me to add the `julia.executablePath`, however even after doing so it still fails to find the binary.

My vscode settings looks like this:
 
```json
  "julia.executablePath": "/home/dom/julia-0.7.0-linux-x86_64/julia-0.7.0/bin/julia",
  "julia.enableTelemetry": true,
```
I'm running vscode 1.28.2 and julia 0.7.0.

**Comment by atranel** [comment]
I think it is because this extensions supports only to version 0.6.4. I have version 1.0.1 and I also wait for new version to make it work inside VS Code. Atom Juno IDE is too slow for my taste and my setup. You can also use IJulia kernel inside Jupyter. It works with new 1.0.1.

**Comment by onetonfoot** [comment]
Yeah I usually use Jupyter but sometimes you need a text editor. Currently using Juno instead with is great but atom can be a little laggy. I've tried with 0.64 but it also didn't work so I don't think its a Julia version issue.

**Comment by davidanthoff** [comment]
Yes, we're working on 1.0 support, but you'll have to wait a little longer.

**Comment by davidanthoff** [comment]
I'm closing this for now. Can you please reopen, if this is still an issue with the v0.11 series? For now we have alphas, but this should work now. https://github.com/JuliaEditorSupport/julia-vscode/releases.
