### ISSUE TITLE
Julia language server is busy

### ISSUE THREAD

**Issue by amerysong** [JuliaEditorSupport/julia-vscode#562]
I installed this extension in vscode marketplace， and set the "julia.executablePath": "/home/amery/Software/julia-1.0.1/bin/julia", but the vs-code keeps saying Julia Language Server is Busy

**Comment by atranel** [comment]
Same. I think it is not compatible with new Julia 1.0.x
Atom Juno IDE works, but Atom is buggy and slow.

**Comment by babaq** [comment]
the Julia-1.0.2 path also doesn't work in windows.

**Comment by skanskan** [comment]
Any solution?

**Comment by Alby407** [comment]
I also can't get it to run on Julia 0.7.0. I get the same "Julia Language Server is busy" message.

**Comment by davidanthoff** [comment]
You'll have to wait for the v0.11 release, I'm afraid.
