### ISSUE TITLE
[feature request] syntax highlight for keyword `primitive`

### ISSUE THREAD

**Issue by singularitti** [JuliaEditorSupport/julia-vscode#565]
I installed the [j1.0alpha4](https://github.com/ZacLN/julia-vscode/tree/j1.0alpha4), written by [ZacLN](https://github.com/ZacLN). However, this version does not support syntax highlighting for `primitive` keyword. Please support it!
Screenshot:
<img width="442" alt="Screenshot" src="https://user-images.githubusercontent.com/25192197/48242231-3f407580-e3a8-11e8-873f-fcfbaf83f574.png">

**Comment by ZacLN** [comment]
Addressed by https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/304
