### ISSUE TITLE
Linter doesn't run on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#57]
I've tracked the problem down to this: we get ``rootPath`` as ``c:\Users\anthoff\source\fund.jl``, but URIs on Windows look like this ``file:///c%3A/Users/anthoff/source/fund.jl/src/helper.jl``. So a simple string comparison doesn't work... I think we should stick with the URI format as our key in the dictionary, because that is the format we need to return in the various JSON messages. But for the comparison we'll have to convert the URI format into a normal windows path format, and then do the comparison in ``isworkspacefile`` based on that.

**Comment by ZacLN** [comment]
I think 

`rootPath=haskey(r.params,"rootPath") ? r.params["rootPath"] : ""`
`server.rootPath = @windows_only replace(replace(rootPath,"\\","/"),"%3A",":")`

replacing  the first line of `process ...{initialize}...` should fix this, can you check?

**Comment by davidanthoff** [comment]
I think I have a more robust fix in #59, but would be good if you could check that one.

**Comment by ZacLN** [comment]
Yep this works
