### ISSUE TITLE
Location printing is non-ideal.

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#574]
Missing a `show` method or something?

<img width="1007" alt="screenshot 2018-11-13 at 21 53 45" src="https://user-images.githubusercontent.com/1282691/48456890-ad14e480-e78e-11e8-998d-a3bbd0fbf975.png">

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/311
