### ISSUE TITLE
Issue with EXCEPTION MethodError

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#585]
Application version: 0.11.0-beta.1
Device type: PC
Event time: 11/14/2018, 8:43:24 PM
Exception type: MethodError
extversion: 0.11.0-beta.1
Failed method: StaticLint.ImportBinding(::StaticLint.Location, ::StaticLint.SIndex{0}, ::String, ::Array{StaticLint.Reference,1})
Operating system: Windows_NT 10.0.17134
Problem Id: MethodError at StaticLint.ImportBinding(::StaticLint.Location, ::StaticLint.SIndex{0}, ::String, ::Array{StaticLint.Reference,1})
Sample Rate: 100
SDK version: node:1.0.6
Session Id: f407b903-964e-47d2-a6e8-723e5680c6b21542254202498
Severity level: Error
Telemetry type: exception
vscodeversion: 1.29.0

<a href="https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/H4sIAAAAAAAAA0WQQU%2BEMBSE%2F8s7U9PSwrJcNTFcPOjGg7fSDooCJaXgmg3%2F3eKy8db0zcz73lzIuCF4bcIr%2FNS6gUoSlMTffnQDhlBZKi%2F0pHvEyefctZotk3EWzGKJwpe5noxvxxC9m5bygkujYFltasWUsCq%2BULNDo5sMBy1Vfoy%2BZ0xu9gaP3s1jtD2g0XMXaE3IjfD6ljfMXZcQlh2FeAaZp5lgKI6CCYGCac0LJmtkprGwqTjQbjjputuwcTb4A5ziJLQ9pqD7bWnKRREzmMhOXJVKlqm6Szl%2F22X3sRqcww3CaPOBfyaPBt7Db%2F2EnzEukgkN16K%2Bnf%2BqAvoqBrxfj6F1%2FQXwWxTpbQEAAA%3D%3D/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://go.microsoft.com/fwlink/?linkid=874159&subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&resourceName=julia-vscode-dev&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522MethodError%2520at%2520StaticLint.ImportBinding(%253A%253AStaticLint.Location%252C%2520%253A%253AStaticLint.SIndex%257B0%257D%252C%2520%253A%253AString%252C%2520%253A%253AArray%257BStaticLint.Reference%252C1%257D)%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222018-11-15T16%253A43%253A24.200Z%2522%252C%2522createdTime%2522%253A%25222018-11-15T06%253A24%253A46.944Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D&func=NavigateToPortalFeature" target="_blank">View similar exceptions in this time range<\a>

**Comment by ZacLN** [comment]
https://github.com/ZacLN/StaticLint.jl/commit/84486bbdf2248de8d382e122a3131488c5f5b0c4
