### ISSUE TITLE
document formatting A'A

### ISSUE THREAD

**Issue by zymbuzz** [JuliaEditorSupport/julia-vscode#587]
I noticed that there should be an exception for A'A matrix formatting. Otherwise, one gets an error

<img width="883" alt="screenshot 2018-11-15 at 14 02 53" src="https://user-images.githubusercontent.com/32014394/48554660-46eba700-e8df-11e8-9e9f-ed90df4b859e.png">

Before:
`a=randn(4,4)
b=a'a`

after:
`a = randn(4, 4)
b = a'  a`

**Comment by ZacLN** [comment]
fixed by https://github.com/ZacLN/DocumentFormat.jl/commit/cd09bbef2bffa30d1a4519794dfc9c99e4555fdd
