### ISSUE TITLE
MethodError: no method matching getindex(::Nothing, ::String)

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#591]
Application version: 0.11.0-alpha.9
Device type: PC
Event time: 11/14/2018, 1:06:00 PM
Exception type: MethodError
extversion: 0.11.0-alpha.9
Failed method: process(::LanguageServer.JSONRPC.Request{Val{Symbol("julia/toggleFileLint")},Nothing}, ::LanguageServerInstance)
Operating system: Windows_NT 10.0.17134
Problem Id: MethodError at process(::LanguageServer.JSONRPC.Request{Val{Symbol("julia/toggleFileLint")},Nothing}, ::LanguageServerInstance)
Sample Rate: 100
SDK version: node:1.0.6
Severity level: Error
Telemetry type: exception
vscodeversion: 1.29.0

<a href="https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/H4sIAAAAAAAAA0WQzU7DMBCE32XPMbJTJzW5goR64QAVB262M4FAEkeOE4qqvjub%2Foib5Z2Z%2FXaO5MOQovXpDXFqw0AVKcr4tx%2FDgCHtaqqO9Gx78ORr7lorlsmHGqLGwsLX2U0%2BtmNi76ql0siN16iF804LrWrNLzixbWxTYGs3urxn3wumMEePpxjmkW2PaOzcJTplFEZEe8sb5q7LCMsVhRRgjG68gCmUUApGGF4ifCFlXjrplFn5z4a9dd2KjYPHGXDiSWp7TMn269JcKsMZQul9ripZVlLe5VK%2FX2UPXA0O6Qbhrf%2FEP1NEgxgR137S78iLNhkNl6J%2BQvzeJfQ7Dvi4HEOn0x%2B4hSR8bQEAAA%3D%3D/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://go.microsoft.com/fwlink/?linkid=874159&subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&resourceName=julia-vscode-dev&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522MethodError%2520at%2520process(%253A%253ALanguageServer.JSONRPC.Request%257BVal%257BSymbol(%255C%2522julia%252FtoggleFileLint%255C%2522)%257D%252CNothing%257D%252C%2520%253A%253ALanguageServerInstance)%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222018-11-15T09%253A06%253A00.204Z%2522%252C%2522createdTime%2522%253A%25222018-11-15T17%253A19%253A33.870Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D&func=NavigateToPortalFeature" target="_blank">View similar exceptions in this time range<\a>

**Comment by davidanthoff** [comment]
Stack trace:
````
MethodError:
   at process(::LanguageServer.JSONRPC.Request{Val{Symbol("julia/toggleFileLint")},Nothing}, ::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\requests\misc.jl50)
   at macro expansion (logging.jl317)
   at run(::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl33)
   at top-level scope (.\scripts\languageserver\main.jl26)
   at top-level scope (none)
   at include (boot.jl317)
   at include_relative(::Module, ::String) (loading.jl1044)
   at include(::Module, ::String) (sysimg.jl29)
   at exec_options(::Base.JLOptions) (client.jl231)
   at _start() (client.jl425)
````
From ``alpha.9``, so might not be a problem with the beta release.

**Comment by ZacLN** [comment]
I think this was a transition bug but have made the method safer anyway in https://github.com/JuliaEditorSupport/LanguageServer.jl/commit/ca8e52f2c2b5d3739cfe8c50b6c2e5faebc0643a
