### ISSUE TITLE
Beta test v0.4.0-beta

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#6]
Please help beta test the next release! To try it out, follow these steps:

1. Download and install VS Code from [here](https://code.visualstudio.com).
2. Download the beta from [here](https://github.com/JuliaEditorSupport/julia-vscode/releases/download/v0.4.0-beta.1/language-julia-0.4.0-beta.1.vsix).
3. Install the extension by running ``code language-julia-0.4.0-beta.1.vsix`` from the directory where you saved the ``language-julia-0.4.0-beta.1.vsix``.
4. Start VS Code and play around.

I would especially welcome testing of the linter. The linter should be triggered by simply opening a .jl file. It will take a while (couple of minutes) until the first linting results are shown when you do this the first time (a lot of package installation and precompilation happening in the background), but then results should show up instantaneously (both as you open a file and edit).

If you tried the beta, please report back here with a comment whether it worked and on what platform you were. Please also report if things worked, not just problems. I am especially looking for people on macOS to try this out (I don't have a Mac).

**Comment by davidanthoff** [comment]
One more thing: if julia is on your path, everything will just work. If it isn't, you have to configure the ``julia.validate.executablePath`` setting. Just open the user settings and search for the julia configuration section.

**Comment by essenciary** [comment]
A first issue I encountered on my Mac is that I've got no `code` binary. A quick googling revealed this: https://code.visualstudio.com/docs/setup/osx. Might want to include it in the instructions.

**Comment by essenciary** [comment]
I think there's a problem with looking for Julia. I get: "Could not start julia.exe for linter process". The ".exe" part doesn't look right to me.

**Comment by davidanthoff** [comment]
@essenciary 

> A first issue I encountered on my Mac is that I've got no code binary. A quick googling revealed this: https://code.visualstudio.com/docs/setup/osx. Might want to include it in the instructions.

Done

> I think there's a problem with looking for Julia. I get: "Could not start julia.exe for linter process". The ".exe" part doesn't look right to me.

Yes, good catch, I should adjust the error message there. Did you try to manually set your path to julia in the ``julia.validate.executablePath`` configuration setting? That should work.

**Comment by essenciary** [comment]
@davidanthoff 
I've added the path and it now works fine 👍 

I'm normally using Sublime so I'm just more or less browsing through files looking for obvious issues.

This is a first thing. On: 
```julia
include(abspath(joinpath("lib", "Genie", "src", "model_types.jl")))
```

The linter looks for the file inside it's own directory and can't find it. It should look for files using the project's path. 
This in turn triggers a multitude of warnings about missing declarations (undeclared symbol) which would otherwise be mixed in. 

Also it would be nice to have a way of copying the linter message, I'd include it here. But also to use it for debugging.

**Comment by davidanthoff** [comment]
@essenciary Thanks a lot!

> The linter looks for the file inside its own directory and can't find it. It should look for files using the project's path. 

I'm just using [Lint.jl]() here, and this is probably something that would have to be fixed in that package itself. My guess is that Lint.jl just can't handle ``include``s that have further function calls in them. Also, ``include`` is always relative to the path of the file where the include appears, *not* to the current working directory or project folder. It also works with using just ``/`` as a path separator on all systems, as far as I can tell. So I think there is no harm in just changing your include to ``include("lib/Genie/src/model_types.jl")``, and then Lint.jl might be able to handle it correctly. Not sure, though.

> Also it would be nice to have a way of copying the linter message, I'd include it here. But also to use it for debugging.

And as for the UI, that is completely out of this extension's hand, that is just the stock UI that VS Code provides, with no option to change anything. Are you on VS Code 1.3? They actually just changed the UI for displaying linter information in that version.

Thanks again!

**Comment by essenciary** [comment]
You're very welcome! If you stumble upon more specific test cases in the future let me know, I'll try them out on the mac. Cheers!

**Comment by essenciary** [comment]
I'm on 1.3.1, yes.
