### ISSUE TITLE
Julia executable not found

### ISSUE THREAD

**Issue by indiejames** [JuliaEditorSupport/julia-vscode#600]
macOS Mojave
Julia 1.0
VS Code 1.29.1
Julia Extension 0.10.3

Every time I open a Julia file I get the following error message:

> Could not start the julia language server. Make sure the configuration setting julia.executablePath points to the julia binary.

The julia binary is in my path, but I have tried setting that configuration parameter anyway and it makes no difference.

**Comment by ZacLN** [comment]
Try our beta for julia 1.0: https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.11.0-beta.2

**Comment by indiejames** [comment]
Thanks, I just tried it, but it crashed. It said it sent a report.

**Comment by omendezmorales** [comment]
Hi Julia VS-code team,
I'm in the process of learning the language, and after installing the beta extension for Julia 1.0 [mentioned above](https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.11.0-beta.2), I also do see the error message of this issue:

> Could not start the julia language server. Make sure the configuration setting julia.executablePath points to the julia binary.

Below my particular settings:

- Julia Version 1.1.0 (2019-01-21)
-  lsb_release: Ubuntu 18.04.2 LTS
- VS Code version: 1.35.1
- path to Julia executable: ~/Downloads/julia-1.1.0/bin/julia

Thanks in advance for your help

**Comment by davidanthoff** [comment]
That is a very old beta release. I would suggest you just install the extension from within VS Code via the marketplace, you'll get a much newer version that way.

**Comment by omendezmorales** [comment]
Thanks for reaching out, @davidanthoff .
I've installed the latest stable version of the extension (0.11.6) and still have the same issue. Attached you can see a screenshot of the error messages I'm getting. I notice that when I clicked on the lower left corner ("Jula env :1.0"), the error message is telling me:

> exited with error code 127

I tried on my commandline and see the same message, so I think the call to launch the executable in _[jlpkgenv.ts](https://github.com/julia-vscode/julia-vscode/blob/2d38dd17ea4e711cfd2898cabfaab48d350ca373/src/jlpkgenv.ts)_ line 50, perhaps should go without quotes, else it does not find it.

What is your advice? Thanks,

![julia-server](https://user-images.githubusercontent.com/6626759/59464949-c3078800-8df7-11e9-9552-8c8ba6387845.png)

**Comment by davidanthoff** [comment]
Ah, wait, if you execute `~/Downloads/julia-1.1.0/bin/julia` on the command line (outside of VS Code), it also doesn't work? That suggests that there is simply something wrong with your julia installation, unrelated to the extension here.

**Comment by omendezmorales** [comment]
If I execute it without the quotes, it does work -I followed the setup instructions illustrated [here](https://www.youtube.com/watch?v=GBcw8qtCSE8). I see however that this VS extension calls the process within quotes, and then it does not work.

**Comment by davidanthoff** [comment]
Hm, not sure what the problem is, to be honest... 

The way I do this on Ubuntu is that I create a symbolic link as suggested [here](https://julialang.org/downloads/platform.html#generic-binaries), and then I just set the config in the VS Code extension to `julia`, maybe you could try that?

**Comment by omendezmorales** [comment]
I solved it: the path I entered above using the ~ for my home directory does not get expanded (into /home/orlando/) and therefore it does not find it. It should be an absolute path instead of a relative. Thanks for your help.

**Comment by davidanthoff** [comment]
https://github.com/julia-vscode/julia-vscode/issues/751
