### ISSUE TITLE
No docstrings for qualified functions

### ISSUE THREAD

**Issue by pfitzseb** [JuliaEditorSupport/julia-vscode#605]
![image](https://user-images.githubusercontent.com/6735977/48891675-51a4bf80-ee3c-11e8-893e-e655a74ca0a4.png)

Works fine for just `sin` though:
![image](https://user-images.githubusercontent.com/6735977/48891720-6b460700-ee3c-11e8-9a73-1ea45c0a39ba.png)

Would also be super cool to render the docstring as markdown :)

**Comment by ZacLN** [comment]
Ta will fix that, however I don't think vscode allows MD for completion docs.

**Comment by pfitzseb** [comment]
Seems like it is possible by [using `MarkdownString`](https://github.com/Microsoft/vscode/issues/1920#issuecomment-331347854).

**Comment by ZacLN** [comment]
Hmm I tried in the past and it didn't work, will have another look

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/317
