### ISSUE TITLE
When will you support for Julia 1.0?

### ISSUE THREAD

**Issue by ConAntares** [JuliaEditorSupport/julia-vscode#608]
Both VScode and Julia are surprise packets for scientistic programming, but, I found this extension version desn't match Julia 1.0. I want to know when will you upgrade with this issue?

**Comment by davidanthoff** [comment]
Yes, use the beta versions for now. We’re trying hard to get them finished, and when they are, we’ll release a new version to the marketplace.

**Comment by ConAntares** [comment]
> 
> 
> vscode v0.11.0 beta works well.
> https://github.com/JuliaEditorSupport/julia-vscode/releases
> 
> Installing it on Windows 10 is straightforward.
> On Windows 7 I first had to install Poweshell 3.0 and enable the latest TLS version.

Thanks a lot for your response. But I am failed on installation, it shows: 
Element 'Identity' has invalid value for attribute 'Version'

**Comment by 8uurg** [comment]
Rather than trying to double-click to open the file, try to do use the 'Install from VSIX' from the vscode panel.
![screenshot1](https://user-images.githubusercontent.com/3746853/48984367-01a75080-f0fb-11e8-9a45-c704193754b9.png)
![screenshot2](https://user-images.githubusercontent.com/3746853/48984384-28fe1d80-f0fb-11e8-8d94-761b8374df99.png)
This works for me (double clicking tries to open in Visual Studio Version Selector, which is not VSCode, and would give that message)

**Comment by mindplay-dk** [comment]
Tried installing `v0.11.0-beta.2` from the VSIX, and it didn't work for me - I just get the exact same "unable to start language service" message as with the current release version.

I'm using Version 1.0.2 (2018-11-08) on 64-bit Win 10.

I tried clicking on the mysterious "Julia env: v1.0" button on the bottom left of the toolbar, and I get the following message:

> Command failed: "C:\julia" --startup-file=no --history-file=no -e "using Pkg; println.(Pkg.depots())" '"C:\julia"' is not recognized as an internal or external command, operable program or batch file. `"C:\julia" --startup-file=no --history-file=no -e "using Pkg; println.(Pkg.depots())"` (exited with error code 1)

I've tried both with and without manually setting `julia.executablePath` to e.g. `C:\julia\bin\julia.exe` where I have it installed, and the message is the same either way, so it looks like it's not parsing the Windows-path correctly maybe? With everything after the first `\` gone missing. Just a guess.

**Comment by skanskan** [comment]
> Tried installing `v0.11.0-beta.2` from the VSIX, and it didn't work for me - I just get the exact same "unable to start language service" message as with the current release version.
> 
> I'm using Version 1.0.2 (2018-11-08) on 64-bit Win 10.
> 
> I tried clicking on the mysterious "Julia env: v1.0" button on the bottom left of the toolbar, and I get the following message:
> 
> > Command failed: "C:\julia" --startup-file=no --history-file=no -e "using Pkg; println.(Pkg.depots())" '"C:\julia"' is not recognized as an internal or external command, operable program or batch file. `"C:\julia" --startup-file=no --history-file=no -e "using Pkg; println.(Pkg.depots())"` (exited with error code 1)
> 
> I've tried both with and without manually setting `julia.executablePath` to e.g. `C:\julia\bin\julia.exe` where I have it installed, and the message is the same either way, so it looks like it's not parsing the Windows-path correctly maybe? With everything after the first `\` gone missing. Just a guess.

You should try again with the julia.executablePath pointing to your  C:\julia\bin\julia.exe  (check if this is really the path) and adding exclusions to your antivirus and firewall.

And try the extension beta1, for me works better.

**Comment by danielruc91** [comment]
On win10 VS code, i am having the following issue:

> "The terminal process command 'C:/Users/Danie/AppData/Local/Julia-1.0.3/bin/Julia -q -i --project=C:\Users\Danie\.julia\environments\v1.0 c:\Users\Danie\.vscode\extensions\julialang.language-julia-0.11.0-beta.2\scripts\terminalserver\terminalserver.jl 13164 'C:\Program Files\Microsoft VS Code\Code.exe' true' failed to launch (exit code: 2)"

I am using the 64 bit version of Julia 1.0.3.

**Comment by littletwolee** [comment]
thx, @mindplay-dk it work on 1.0 version

**Comment by davidanthoff** [comment]
@danielruc91 Could you describe exactly what you do after you start VS Code to get that error message?

There is a backslash missing in what we are trying to run there, but I don't understand why it is missing :)

**Comment by danielruc91** [comment]
> @danielruc91 Could you describe exactly what you do after you start VS Code to get that error message?
> 
> There is a backslash missing in what we are trying to run there, but I don't understand why it is missing :)

Hi, thanks for replying. I think the most recent beta 0.11.0-beta.2 has solved the problem. Now i can start the extension without problem. Thanks!

**Comment by davidanthoff** [comment]
Fantastic!

**Comment by davidanthoff** [comment]
Alright, extension version 0.11.0 is published to the marketplace and supports julia 1.0. Thanks for being patient!
