### ISSUE TITLE
Strange error in VS code input

### ISSUE THREAD

**Issue by skanskan** [JuliaEditorSupport/julia-vscode#610]
Hello.

I've been using Julia on VS code for several days but today it doesn't work. I don't know why.
Maybe it's because now I'm using it with language-julia-0.11.0-beta.2.vsix 

Whatever I try to run on the main editor it adds it a prefix "200~" and generates an error.

For example:
`using DataFrames, GLM`

produces:
```
200~using DataFrames, GLM
ERROR: MethodError: no method matching ~(::Int64, ::Int64)
Closest candidates are:
  ~(::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) at int.jl:274
  ~(::Integer) at int.jl:138
Stacktrace:
 [1] top-level scope at none:0
```

Has anyone had the same problem?
Do you think is a problem wit VS Code, the extension or with Julia?
running the code directly on the REPL works well.
I've tried reinstalling the extension but the problem is still there.
I've also tried reinstalling a different version of VS Code.

PD:  I've reinstalled the beta1 and it works but beta2 doesn't.

**Comment by KristofferC** [comment]
Probably a problem with https://github.com/JuliaEditorSupport/julia-vscode/pull/596.

It works fine for me on Mac. Is this on windows?

**Comment by kafisatz** [comment]
yes, I have this issue on windows.
Beta 1 works for me too.

```

julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_BINDIR = C:\Julia-1.X\bin\
  JULIA_EDITOR = C:\Program Files\Microsoft VS Code\Code.exe
  JULIA_HOME = C:\Julia-1.X\bin\

```

**Comment by KristofferC** [comment]
Perhaps we should revert https://github.com/JuliaEditorSupport/julia-vscode/pull/596 or conditionally disable it on Windows?

**Comment by ZacLN** [comment]
I'll add a config option for this that defaults to disabled on windows

**Comment by arnavs** [comment]
@ZacLN any luck with the config? would be great to be able to use this on my Windows box at work
