### ISSUE TITLE
The formatter seems to produce an extra "d" at the end of the file for some reason

### ISSUE THREAD

**Issue by x-ji** [JuliaEditorSupport/julia-vscode#612]
Test case:

```julia
function a(b) 
    b
end
```

Output:

```julia
function a(b) 
    b
endd
```

This always happens to the last function of the file.

It's particularly weird since by `using DocumentFormat` and then `DocumentFormat.format()` directly on a string, this doesn't seem to happen. So maybe something is wrong with the integration of that module in this plugin, or it could be something wrong with my vscode config?

Version: v0.11.0 beta 2

**Comment by ZacLN** [comment]
Should be fixed by https://github.com/JuliaEditorSupport/LanguageServer.jl/commit/deb7427538a1a2f433f3eea988c624ad37d85fcb
