### ISSUE TITLE
Arrow keys and DELETE not working in new 0.11 beta2

### ISSUE THREAD

**Issue by atranel** [JuliaEditorSupport/julia-vscode#614]
When I use plotting I lose arrow keys and DELETE functions in editor. I cannot move using arrow keys or use DELETE, but mouse pointing the cursor and BACKSPACE deleting work.  I installed 0.10.3 with Julia 0.64 and where it works OK.

**Comment by atranel** [comment]
When I switch off new option Use Revise, the problem is gone.

**Comment by atranel** [comment]
It seems, that Use Revise is cause of problem. If I switch it OFF, the cursor problem doesn't happen.

**Comment by davidanthoff** [comment]
Uh, now that is weird... I have no idea how that could possibly related...

**Comment by atranel** [comment]
Hmm, it was just luck I guess. It doesn't help now 🤔

**Comment by davidanthoff** [comment]
I'm moving this back to v0.11.1 because right now I don't know what to do about this.

**Comment by davidanthoff** [comment]
Actually, I think @EricForgy's PR https://github.com/JuliaEditorSupport/julia-vscode/pull/641 probably solved this! I'm closing for now, if this occurs again with a new beta, please reopen!
