### ISSUE TITLE
Another formatting issue

### ISSUE THREAD

**Issue by zymbuzz** [JuliaEditorSupport/julia-vscode#616]
After formatting the document, the error comes up

Before:
`round.(5.3 - 5.2; digits=0)`

After:
`round.(5.3 - 5.2digits = 0)`

However, all is fine for command (no dot '.'):
`round(5.3 - 5.2; digits = 0)`

**Comment by ZacLN** [comment]
https://github.com/ZacLN/DocumentFormat.jl/commit/248bc75a0aaff70ed696c85222a92812fe7340a5
