### ISSUE TITLE
Selected path is not a julia environment

### ISSUE THREAD

**Issue by Roger-luo** [JuliaEditorSupport/julia-vscode#617]
When I try to use a package folder as my environment (with `Project.toml`, etc.)

![image](https://user-images.githubusercontent.com/8445510/49482879-e88b5780-f7fe-11e8-961d-5b487ff57976.png)

I got this error

![image](https://user-images.githubusercontent.com/8445510/49482887-f4771980-f7fe-11e8-9989-9a988917c3e4.png)

It seems that the editor can't recognize what's outside `.julia`?

**Comment by Techbot121** [comment]
probably related to this https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/316

**Comment by Techbot121** [comment]
yeah I just digged around a bit and it's straight up not implemented yet
the extension calls `julia/activeenvironment` in
https://github.com/JuliaEditorSupport/julia-vscode/blob/master/src/jlpkgenv.ts#L23
if you select a folder, which is not implemented yet see
https://github.com/JuliaEditorSupport/LanguageServer.jl/commit/f2dd7bd87278eac6aba83ec8ef712103a867a515

(actually that commit is missing in the submodule, which actually errors)

**Comment by dboyliao** [comment]
@Roger-luo I run into this recently in my source-build julia environment.
I run the julia interpreter and enter package mode then run `update`.
Reselect the environment path in VSCode and the problem solved.

**Comment by bocaguy** [comment]
Is learning Julia going to be another hair-pulling process where I spend 3/4 of time on StackOverflow learning about existing bugs and finding out about a lot of non-intuitive tweaks?

Sorry, if that's the case, I don't care about the B.S. "easy/fast" vs "hard/fast" nonsense...Python and C++ are faster and established.

Julia developers, come back to me when your language is fully mature without all the painful setup nonsense.
