### ISSUE TITLE
Adding arguments to `julia.executablePath`

### ISSUE THREAD

**Issue by bhvieira** [JuliaEditorSupport/julia-vscode#619]
I'm currently on Julia 0.7.0 and JuliaLS 0.10.3

Julia 0.7 has deprecation warnings all over the place. It's possible to suppress them with `--depwarn=no` on bash, and I think I could write a script which would allow me to do it in vscode as well.

The integrated terminal has a `terminal.integrated.shellArgs.linux` setting though, perhaps something like that could be implemented for `julia` settings?

I don't know how useful it would be to other users, so it's mainly a suggestion.

**Comment by davidanthoff** [comment]
We just merged a PR on master that has this functionality, will ship with the next release.
