### ISSUE TITLE
missing last enter with ctrl-enter eval

### ISSUE THREAD

**Issue by phlavenk** [JuliaEditorSupport/julia-vscode#621]
Whenever I enter a syntactic block line-by-line by hitting ctrl-enter, I get an issue at the last line. Even though I do ctrl-enter on the line with closing `end` statement, the line is copied into REPL console but the end-of-line is not. Therefore I have to switch to the REPL and press enter manually. This worked in previous alpha releases.
Julia 1.0.2, Win7-64, VSCode with 11-beta2 julia extension.

**Comment by davidanthoff** [comment]
I can't replicate this... Could you post a file that I can then just step through with Ctrl+Enter that triggers this?

**Comment by phlavenk** [comment]
I can confirm this is a solved issue on RC2. Closing.
