### ISSUE TITLE
invalid escape sequence

### ISSUE THREAD

**Issue by mahdizakizadeh** [JuliaEditorSupport/julia-vscode#639]
on 0.11.0 beta 2
this is what happened in my terminal
when I wanted to run the code (press F5):
```
julia> include("c:\dev\julia\main.jl")

ERROR: syntax: invalid escape sequence
```
(Also I had to press enter after include manually!)

**Comment by davidanthoff** [comment]
This is already fixed on ``master``, next beta should not have that problem.
