### ISSUE TITLE
IOError: stat: invalid argument (EINVAL)

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#646]
Application version: 0.11.0-rc.2
Event time: 12/31/2018, 12:15:43 PM
Exception type: Base.IOError
extversion: 0.11.0-rc.2
Failed method: stat(::String)
Operating system: Windows_NT 10.0.17763
Problem Id: Base.IOError at stat(::String)
Severity level: Error
vscodeversion: 1.30.1

<a href="https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/H4sIAAAAAAAAA0WQT0%2BEMBTEv8s7U9PSsn%2B4amK4eNCNB29tGRQFSkqLazZ8d4vLxlvTNzPv9%2BZC1g3Baxte4afWDVSSoCz99qMbMISqpvJCT7pHmnzGrtVsnqyrwWrMSfgSzWR9O4bkXbW0O3BpFWpmrFFMiVqlFwzbN7opsNdS7Y7J94zJRW%2Fx6F0ck%2B0BjY5doCUjN8LrW94Quy4jzBsKITcSwgrGa3lgQuDIDIdmKIqm2OdaNlzSZjhp063YOFv8AU5pEtoeU9D9ujTnImXkTIpTzktRlErecV68bbL7VA3O4QZhtf3AP5NHA%2B%2Fh137Cz5gWyYyGa1Hfzn9VAX2VAt6vx9Cy%2FALJg0YDbQEAAA%3D%3D/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://go.microsoft.com/fwlink/?linkid=874159&subscriptionId=6803c4ed-bcb4-41d4-bceb-7faf5e7a3469&resourceGroup=Default&resourceName=julia-vscode-dev&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522Base.IOError%2520at%2520stat(%253A%253AString)%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222019-01-01T08%253A15%253A43.005Z%2522%252C%2522createdTime%2522%253A%25222019-01-02T01%253A17%253A01.878Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D&func=NavigateToPortalFeature" target="_blank">View similar exceptions in this time range<\a>

**Comment by davidanthoff** [comment]
Stack trace:
````
Base.IOError:
   at stat(::String) (stat.jl68)
   at ispath (stat.jl303)
   at process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.CompletionParams}, ::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\requests\textDocument.jl305)
   at macro expansion (logging.jl317)
   at run(::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl33)
   at top-level scope (.\scripts\languageserver\main.jl26)
   at top-level scope (none)
   at include (boot.jl317)
   at include_relative(::Module, ::String) (loading.jl1044)
   at include(::Module, ::String) (sysimg.jl29)
   at exec_options(::Base.JLOptions) (client.jl231)
   at _start() (client.jl425)
````

**Comment by schlichtanders** [comment]
I get this very error after installing Atom Juno and julia-vscode and trying to add a local julia package with ``] dev mypackage``

**Comment by schlichtanders** [comment]
sorry, my mistake... I should have used ``] dev /absolute/path/to/mypackage`` and now it works

**Comment by peteristhegreat** [comment]
This issue happens with Julia 1.0.4 when trying to dev a package that is on a different drive than the drive Julia is installed on.
