### ISSUE TITLE
julia 1.1 compatability

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#647]

**Comment by davidanthoff** [comment]
The real issue is https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/320, that makes the extension break on julia 1.1 currently.

I propose that we make v0.11.3 a minimal bug fix release that only fixes that one thing.

**Comment by zhopan77** [comment]
Thank you! I just updated to extension v0.11.3 but the language server is still crashing when used with Julia 1.1.0.

The exact error message is "The julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. Source: Julia (Extension)".

When I point the extension to Julia 1.0.3 binary the extension v0.11.3 does not crash.

This behavior (crashing under Julia 1.1.0 but not under 1.0.3) seems to be the same as v0.11.2 to me.

I am running Visual Studio Code Version 1.30.2 (Electron 2.0.12) on Windows 10 64-bit (10.0.15063).

**Comment by zhopan77** [comment]
v0.11.4 Julia language server won't crash with Julia 1.1.0 anymore. However, all the hovering functions, go to definition, refractoring, reformatting functions are not working yet.

**Comment by davidanthoff** [comment]
Yes, we still haven't fixed this properly... Sorry, turns out to be more involved than we thought.

**Comment by otobrzo** [comment]
No hovering, no IntelliSense, no Linter...
Any progress to fix it? 

Cheers

Julia lang. supp. 0.11.4
Julia 1.1
VS Code 1.32.2

**Comment by davidanthoff** [comment]
No progress, I'm afraid...

**Comment by haberdashPI** [comment]
Just want to report that whatever is going wrong here is not always going wrong: I have no problem using code completion, hints, hover, etc... with VSCode and Julia v1.1.

**Comment by crstnbr** [comment]
Related discussion: https://discourse.julialang.org/t/am-i-too-stupid-to-use-the-julia-vscode-plugin/22353

**Comment by tribut** [comment]
The problem only happens while loading new packages. So, if you are using the same packages that you used with julia 1.0, you'll be fine. It is only when the language server tries to load something that it hasn't stored you will experience problems. See https://github.com/JuliaEditorSupport/SymbolServer.jl/pull/22/commits/f1d91374078a82a174f9dfb3a2d7446f7c25a48b for details.
