### ISSUE TITLE
Use of possibly undeclared variable: @code_warntype

### ISSUE THREAD

**Issue by kellertuer** [JuliaEditorSupport/julia-vscode#658]
When using `@code_warntype` in a Skript, the Julia language server reports that that might refer to an undeclared (missing) variable.

**Comment by ZacLN** [comment]
`@code_warntype` is exported from `InteractiveUtils`  rather than Base or Core. It's available when using the REPL but not in a script unless imported. You'll need to include `using InteractiveUtils` somewhere

**Comment by kellertuer** [comment]
Thanks for the explanation, I wasn't aware of that. With the additional line of including `InteractiveUtils` it works like a charm :)
