### ISSUE TITLE
Parsing error on keyword argument "type"

### ISSUE THREAD

**Issue by andyljones** [JuliaEditorSupport/julia-vscode#659]
Minimal example:

```julia
foo(;type) = nothing
foo(type="test")
```

which is valid Julia, but gives a whole pile of warnings and errors:

<img width="227" alt="screenshot 2019-01-10 at 07 57 57" src="https://user-images.githubusercontent.com/662606/50954168-8aacf800-14ad-11e9-8520-dfb628997450.png">

<img width="698" alt="screenshot 2019-01-10 at 08 00 02" src="https://user-images.githubusercontent.com/662606/50954267-c21ba480-14ad-11e9-88bf-ba2a5ab932a5.png">

This is with the 0.11.1 extension, vscode 1.30.1, and Julia 1.0.3.

This arose because  PlotlyJS makes heavy use of a 'type' keyword arg, so unfortunately it's not as easy as 'don't use that keyword'.

If you can point me towards the chunk of code that's the likeliest suspect, I'm happy to take a hack at fixing this. Might also need some tips on workflow.

**Comment by ZacLN** [comment]
Oops, I forgot to remove that syntax on the move to 1.0, fixed: https://github.com/ZacLN/CSTParser.jl/commit/24c51db7e643751a707efced476129b3e03b0df7
