### ISSUE TITLE
show current working directory's env?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaEditorSupport/julia-vscode#661]
The environment only shows what's in `.julia`, but it would be convenient if we could show (or just use it as default) when a standard julia project is detected, e.g

when open a `JuliaProject` folder which contains `Project.toml`

```sh
code JuliaProject
```

The environment is changed to this project's env by default, and will be show in the menu instead of pick a folder.

**Comment by davidanthoff** [comment]
Yes, I agree, that is how we should do it!

I think there is one twist: I'd say that if there is a ``Project.toml`` *and* a ``Manifest.toml``, in the root folder, we activate it right away. If there is just a ``Project.toml``, then one is probably editing a package, and in that case I don't think we should activate it, because the more useful workflow to me seems to be to edit that in the context of some other env.

We also need to figure out how this interacts with multiple root folders in the workspace...

**Comment by Roger-luo** [comment]
What about the following strategy:

1. if `Project.toml` and `Manifest.toml` exists, activate current folder
2. if `Project.toml` exists but there's no `Manifest.toml`, check whether the parent folder is `dev`, if it is `dev`, check if `Project.toml` and `Manifest.toml` exists in `../../`, if exists activate, if not use default global environment.

In my case, I prefers local environment (this allows to quick access to whatever you are editing), and global custom environments are rarely used. I guess after 1.0 Julia's workflow is getting consistent to other scripting language, like python.

**Comment by davidanthoff** [comment]
What would be the directory structure where 2. makes sense? We would essentially be checking whether there is a Project/Manifest combo in `~/.julia`, right? That seems not ideal, I don't think it is recommended to have them there?

**Comment by Roger-luo** [comment]
Current `Pkg` allows users to define a project folder with `dev --local`, e.g

```
CustomENV
├── Manifest.toml
├── Project.toml
├── dev
│   ├── Atom
│   │   └── Project.toml
│   └── Blosc
│       ├── Manifest.toml
│       └── Project.toml
└── src
    └── CustomENV.jl
```

Thus, you can't just search if there's a `Project/Manifest` combo in `.julia` only, but have to search local folder (nearest folder) first.

I modified a little bit, this generally just follow `julia --project` behaviour:

1. if user type `code Atom` inside `CustomENV/dev`, it didn't find `Manifest.toml`, but since the user intends to open the project, we should use this `Project.toml` file as environment anyway, so it should execute `instantiate`, since open a folder in VScode means open a project, I guess?

2. if user type `code .` inside `CustomENV/dev`, it can't find `Project.toml/Manifest.toml` in current path, then check if this folder is called `dev`, if it is `dev` then try to find the local env file `Project.toml` and open this environment. if not, use default environment in `.julia/environment/v($JULIA_VERSION)`

I found a lot people using `julia --project` as their compiler binding in CLI, since it is not convenient at all to have everything (to develop) inside `.julia`, is it? So similar behaviour with `--project` would be more convenient and more consistent for users from other languages.

Say, if I just `git clone` instead of `dev` a url, I would just type `code TheFolder`, or I have to exit `REPL` and then cd to `.julia/dev` and `code TheFolder`.

**Comment by davidanthoff** [comment]
Ah, I didn't know about `dev --local`! Yes, then I think that makes a lot of sense.
