### ISSUE TITLE
Use of deprecated `@schedule` macro in known issues wiki page.

### ISSUE THREAD

**Issue by venuur** [JuliaEditorSupport/julia-vscode#662]
In the [known issues wiki page](https://github.com/JuliaEditorSupport/julia-vscode/wiki/Known-issues-and-workarounds) for the Revise package,  the workaround shows the following code snippet:

```julia
atreplinit() do REPL
    @schedule begin
        sleep(0.1)
        try
            @async using Revise
        catch err
            warn("Could not load Revise.")
        end
    end
end
```

The `@schedule` macro is [deprecated](https://github.com/JuliaLang/julia/pull/28800) so the workaround fails for Julia 1.0. I am not sure what the correct replacement is.

**Comment by singularitti** [comment]
Please, solve this! I am having the same trouble.

**Comment by davidanthoff** [comment]
I now replaced these instructions with
```julia
atreplinit() do repl
    @async try
        sleep(0.1)
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
        @warn("Could not load Revise.")
    end
end
```
That seems to work, but I actually don't really understand why we need all of these complications in the first place :) @KristofferC do you have an idea?

Note also, that we also have a config option `useRevise` now that loads Revise.jl at startup of the REPL that you could use instead.
