### ISSUE TITLE
Can't start Julia Language Server of a  conda env of Julia !

### ISSUE THREAD

**Issue by NeutronT** [JuliaEditorSupport/julia-vscode#667]
I installed Julia1.03 through Miniconda3 in Linux, and the problem is that it can't start Julia Language Server.

**Comment by davidanthoff** [comment]
Can you start a REPL inside VS Code with the ``Julia: Start REPL`` command?

**Comment by davidanthoff** [comment]
I'm closing this for now as we don't have enough info to do anything about it. @NeutronT if you have follow up info for us, please reopen!
