### ISSUE TITLE
Support Outline view

### ISSUE THREAD

**Issue by tk3369** [JuliaEditorSupport/julia-vscode#668]
The Outline view is empty.  Could we enable it to show functions from a module?

**Comment by davidanthoff** [comment]
Actually, it does show things on my system.

**Comment by davidanthoff** [comment]
@tk3369 I'm closing for now, but if you have some more info how we can reproduce this, please reopen and let us know!

**Comment by tk3369** [comment]
Yes it works now. I must have an old version before. Thanks for closing it.

**Comment by Elycoo** [comment]
I'm not sure if I should open new issue.
Anyway, I think that there is a conflict with other extension - when I use the [multiCommand](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) extension k;the outline (and other feature like auto completion) not working good.

There is any solution for that?
