### ISSUE TITLE
Problem with default env

### ISSUE THREAD

**Issue by dialvarezs** [JuliaEditorSupport/julia-vscode#670]
OS: OpenSUSE Tumbleweed
Julia: 1.1

I upgraded from Julia 1.0 to 1.1... Basically installed 1.1, reinstalled the packages, deleted the 1.0 environment and all the compiled packages for that version.
And now the extension is not working. When I open vscode, the "env" in the interface appears always as v1.0, and when I click it the only option is v1.1. So I select it, and in the interface nothing happens at all, but completion is not working.
![captura de pantalla de 2019-01-25 13-23-57](https://user-images.githubusercontent.com/13831919/51758511-a0710e80-20a4-11e9-80b1-1216f8a95475.png)

In the devtools the errors appear when I select the 1.1 env:
![captura de pantalla de 2019-01-25 11-53-05](https://user-images.githubusercontent.com/13831919/51758011-7f5bee00-20a3-11e9-947f-f3084423557a.png)

And when I start vscode (before selecting the 1.1 env) I see this running:
`julia --startup-file=no --history-file=no main.jl /home/darkxhunter/.julia/environments/v1.1 --debug=no /tmp/vscode-language-julia-lscrashreports-9586`

I tried reinstalling the extension, but it's still not working.

**Comment by davidanthoff** [comment]
@dialvarezs I'm closing for now because I'm assuming that this was just due to us not supporting julia 1.1 at all when you opened this issue. If this is still an issue, please reopen!
