### ISSUE TITLE
IntelliSense stopped working completely 

### ISSUE THREAD

**Issue by allochi** [JuliaEditorSupport/julia-vscode#673]
Hi,

I just installed the extension, wrote one file and code IntelliSense was working fine, and then it stopped completely, it wouldn't even suggest `println`, nothing, other languages work fine.

I tried couple of workarounds, remove the plugin completely and reinstalled it, turned `ls_debug_mode` to true and restarted vscode, nothing is working.

Could you please help, thanks!

**Comment by yongheekim-dev** [comment]
Same thing happened to me. maybe installing Julia 1.1.0 has something to do with this? 
But using Julia 1.0.3 on julia-vscode doesn't seem to solve this issue.

**Comment by allochi** [comment]
Hi, I never had any other version than Julia 1.1.0, I'm new to it. But it used to work, and suddenly it stopped.

**Comment by davidanthoff** [comment]
Things are broken on julia 1.1 right now, I'm afraid...

**Comment by HP199731** [comment]
Same thing happened to me. The version of Julia is **1.1.0**

**Comment by glalonde** [comment]
> Same thing happened to me. maybe installing Julia 1.1.0 has something to do with this?
> But using Julia 1.0.3 on julia-vscode doesn't seem to solve this issue.

For me as well. It was working on 1.0.3, then I swapped to 1.1.0, and everything stopped, and then I swapped back, and it doesn't seem to have recovered functionality.

**Comment by davidanthoff** [comment]
You could try to delete the extension folder from the ``.vscode`` extensions folder, and reinstall it. I suspect something is messed up with the cache we create.

**Comment by HP199731** [comment]
> 
> 
> > Same thing happened to me. maybe installing Julia 1.1.0 has something to do with this?
> > But using Julia 1.0.3 on julia-vscode doesn't seem to solve this issue.
> 
> For me as well. It was working on 1.0.3, then I swapped to 1.1.0, and everything stopped, and then I swapped back, and it doesn't seem to have recovered functionality.

I may have found a solution. I deleted the. Julia folder in the document folder and restarted vscode. I think the reason for not working may be that I changed the default Julia 1.0 environment of the plug-in to 1.1 environment.

**Comment by HP199731** [comment]
> 
> 
> You could try to delete the extension folder from the `.vscode` extensions folder, and reinstall it. I suspect something is messed up with the cache we create.

Thank you for your reply. I have found a solution. By the way, can this plug-in work in the Linux version of vscode? I didn't find the execution file in linux. My Linux distribution is Pop!_OS, based on Ubantu.

**Comment by davidanthoff** [comment]
Yes, it should work on Linux! You might have to manually configure the path to your julia executable in the julia user setting of the VS Code settings.

**Comment by HP199731** [comment]
> Yes, it should work on Linux! You might have to manually configure the path to your julia executable in the julia user setting of the VS Code settings.


Thank you. I've found the path to the executable file.

**Comment by cenkt** [comment]
Can it be related to the name of "C:\Users\username\.julia\environments\v1.1" directory? When I change it to "C:\Users\username\.julia\environments\v1.1.0" it seems to work.

**Comment by lautaroem1** [comment]
> Can it be related to the name of "C:\Users\username\.julia\environments\v1.1" directory? When I change it to "C:\Users\username\.julia\environments\v1.1.0" it seems to work.

I second this solution. Updated Julia from 1.0.2 to 1.1.0 and everything stopped working.
I just changed the folder name from "1.1" to "1.1.0" and it's working again.

**Comment by davidanthoff** [comment]
That is very weird and I don't understand why that would make a difference, to be honest...

**Comment by cenkt** [comment]
The only problem with this solution is that Julia Pkg does not recognize the folder...

**Comment by allochi** [comment]
Hi, it stopped for me again. I'm on MacOS with Julia v1.1.0

I noticed that at the status bar says `Julia env: v1.0`, although I don't have it installed, now even when I change it to `Julia env: v1.1` it doesn't work, I'm guessing something already went wrong when it didn't find `v1.0` and the IntelliSense stopped working.

I tried to trick it with a symlink `v1.0` to `v1.1` without luck. I tried to trick it by renaming the environment folder to `v1.0` or `v1.1.0` again without luck.

Removing the extension and reinstalling it didn't work this time too.

I'm trying to look into the extension source code, hopefully I'll find something, if I do I will share it.

**Comment by allochi** [comment]
I don't think this is the extension fault anymore, today while I was debugging I noticed vscode status showing alert icon next to `julia`, when I hovered over it, it said, `Julia language is not enabled`.

I completely removed Julia and reinstalled it, and everything is back, and the IntelliSense started to work again.

So - steam out a little - Julia managed to add the reinstallation time to it's already JIT time for me to write and run my code, I hope something get fixed in the next release.

**Comment by allochi** [comment]
Unbelievable it stopped again!

**Comment by anshu957** [comment]
For some unknown reason, renaming the folder v1.1 to v1.1.1 solves the problem as mentioned above. However, better solution is to create a symbolic link to v1.1 and name it as v.1.1.1. That way all the installed packages and their dependencies remains intact.

**Comment by Karlheinzniebuhr** [comment]
same issue on win10

**Comment by davidanthoff** [comment]
@Karlheinzniebuhr could you open a new issue about this, with some more info? What version of Julia etc? Thanks!
