### ISSUE TITLE
"Select environment" dialog box freezes

### ISSUE THREAD

**Issue by janpipek** [JuliaEditorSupport/julia-vscode#675]
When I try to change the environment to a package directory ("Pick a folder"), the (system-rendered) folder selection dialog opens but it is not possible to interact with it apart from closing it by ESC key. Selecting an installed Julia's default environment (in the little vs code popup) works.

Setup:
- Ubuntu 16.04 (+ KDE)
- VS Code 1.30
- julia-vs-code 0.11.4
- julia 1.0.1 or 1.1.0

Any ideas why this happens? Any specifics that would help spot the problem?

Thanks, Jan

P.S. I understand that this might be a problem of VS Code itself.

**Comment by janpipek** [comment]
Additional note: It would be awesome if you could specify the environment in VS code project's config.

**Comment by davidanthoff** [comment]
@janpipek is this still an issue?

**Comment by janpipek** [comment]
Sorry, forgot to follow up. Yeah, it does not freeze anymore and I am able to select the environment!

Thank you.
