### ISSUE TITLE
F12 Navigation not working

### ISSUE THREAD

**Issue by Wikunia** [JuliaEditorSupport/julia-vscode#677]
version 0.11.4
julia version 1.1 (somehow it always shows environment v1.0) don't know how to change that for ever.

I'm not able to use F12 or right click jump to definition. It didn't work for a while and then started working again and now it doesn't work anymore without actively changing anything.

I tried to disable the extension and enable it again without effect as well as restarting visual studio code.

**Comment by davidanthoff** [comment]
@Wikunia I'm going to close this for now because I assume this was due to us simply not supporting julia 1.1 at the time when you opened this issue. If this bug is still present with the current version of the extension, please reopen this issue!
