### ISSUE TITLE
null displayed in the plot pane

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaEditorSupport/julia-vscode#678]
When displaying plots in the plot pane there is a `null` displayed next to the plot (see screenshot, bottom left of the plot).
![image](https://user-images.githubusercontent.com/11876271/53207583-e9a37800-35e8-11e9-8513-7633456cdf7f.png)

**Comment by davidanthoff** [comment]
I can't replicate that. Is this still an issue with the latest version of the extension?

**Comment by MaximeBouton** [comment]
I cannot replicate either with the latest version, it might be fixed.

**Comment by davidanthoff** [comment]
Great!
