### ISSUE TITLE
Race condition with precompile

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#7]
There is a race condition with precompile right now. Julia 0.5 has the `--compilecache=no`, which we should try for the linter process once we switch to julia 0.5.

**Comment by davidanthoff** [comment]
@ZacLN I've added the ``--compilecache=no`` now. This probably slows things down at startup, but I couldn't find any other way around this race condition. The race condition is that if you start two instances of VS Code at the same time, and the private package folder is not yet pre-compiled, things crash.

I think our best bet is to hope that julia itself fixes the race condition eventually, and then reenable package precompile...

**Comment by davidanthoff** [comment]
Disabling pre-compile was really too slow... Leaving this for now, have to think of something better eventually.

**Comment by ZacLN** [comment]
Is this still a problem?

**Comment by davidanthoff** [comment]
Haven't heard any complaints, so lets close it.
