### ISSUE TITLE
Julia path on Linux

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaEditorSupport/julia-vscode#706]
I just can't figure out what's the right path to set in `Julia: Executable Path` in VSCode. Julia is already in my path and the directory is `/home/jd/julia/usr/bin/julia`. I can launch julia from the terminal using `julia` command directly. Why doesn't setting this path work in VSCode?

**Comment by davidanthoff** [comment]
Does it work if you leave the setting empty? If you just put in `Julia`? The latter should work with https://github.com/JuliaEditorSupport/julia-vscode/pull/688. 

If all fails it should be enough to put in the full path to the Julia binary.
