### ISSUE TITLE
No weave preview

### ISSUE THREAD

**Issue by pablosanjose** [JuliaEditorSupport/julia-vscode#733]
I think Weave.jl support is currently broken.

This simple `test.jmd` fails to produce any preview with the v0.11.6 release and vscode v1.34.0
```
# Testing

Nothing shows up
```

The only output in the console is
```
Weaving preview of /var/folders/5q/frmlpx8167x8pvn1vhh0nyv00000gq/T/julia-vscode-weave119424-72046-13ukbby.ker9/source-file.jmd
[ Info: Ignore
[ Info: Report weaved to /var/folders/5q/frmlpx8167x8pvn1vhh0nyv00000gq/T/julia-vscode-weave119424-72046-13ukbby.ker9/output-file.html
```

This is on macOS 10.14.5

EDIT: same problem under 0.12.0 alpha
EDIT2: the actual file `/var/folders/5q/frmlpx8167x8pvn1vhh0nyv00000gq/T/julia-vscode-weave119424-72046-13ukbby.ker9/output-file.html` does exist, but it is not shown in vscode.

**Comment by davidanthoff** [comment]
Yes, the problem is that VS Code deprecated the API we were using for the preview. We just have to migrate the whole weave preview stuff to the new webview API. Shouldn't be too complicated, but until that is done, it just won't work.

**Comment by davidanthoff** [comment]
But lets leave it open, we _do_ need to fix this :)
