### ISSUE TITLE
No symbols (only module) is shown when the source file is a module file (one module block)

### ISSUE THREAD

**Issue by ghost** [JuliaEditorSupport/julia-vscode#78]
This case should be treated, maybe by reparsing the module block after droping the line contains "module   "

**Comment by davidanthoff** [comment]
I'm almost tempted to move this to v0.6.0, unless it is easily and quickly (today) fixed for 0.5.0. @ZacLN, what do you think?

**Comment by ZacLN** [comment]
Hmm this is complicated, we can just ignore modules by changing https://github.com/JuliaEditorSupport/julia-vscode/blob/master/scripts/languageserver/parse.jl#L71 to

` if isa(ex, Expr) && ex.head in[:incomplete, :error, :module]`

but to get all this information properly we're really going to have to get JuliaParser extended

**Comment by davidanthoff** [comment]
@ZacLN So I think the options for v0.5.0 are 1) do nothing about this, or 2) make the small change you suggested. I'll let you decide which one is better for v0.5.0, but if we want to do something about this for v0.5.0 it would be great if we could merge that today, so that it is in the beta build.

**Comment by ZacLN** [comment]
I haven't had a chance to test it so I'd leave it as s for the moment. I'll test and merge the other prs in a few hours when I get home

**Comment by davidanthoff** [comment]
Ok, so we'll fix this for 0.6.0.
