### ISSUE TITLE
incomplete latex snippets

### ISSUE THREAD

**Issue by Ken-B** [JuliaEditorSupport/julia-vscode#95]
I was able to crash it again. Sorry :) This time playing with the latex completions.

I've noticed not all latex symbols are available, eg `"\\^2"`. Also doing two right after one another wont work (eg. βᵢ).

Here's the output on error. Again, let me know what I can do to assist.
```
ERROR: LoadError: UnicodeError: invalid character index
 in slow_utf8_next(::Array{UInt8,1}, ::UInt8, ::Int64) at ./strings/string.jl:67
 in next at ./strings/string.jl:92 [inlined]
 in getindex(::String, ::Int64) at ./strings/basic.jl:70
 in next at ./strings/types.jl:113 [inlined]
 in search(::RevString{String}, ::Array{Char,1}, ::Int64) at ./strings/search.jl:12
 in rsearch(::String, ::Array{Char,1}, ::Int64) at ./strings/search.jl:162
 in bslash_completions(::String, ::Int64) at ./REPLCompletions.jl:364
 in completions(::String, ::Int64) at ./REPLCompletions.jl:455
 in process(::JSONRPC.Request{Val{Symbol("textDocument/completion")},TextDocumentPositionParams}, ::LanguageServer) at /Users/ken/.vscode/extensions/julialang.language-julia-0.5.0-beta.3/scripts/languageserver/provider_completions.jl:4
 in run(::LanguageServer) at /Users/ken/.vscode/extensions/julialang.language-julia-0.5.0-beta.3/scripts/languageserver/languageserver.jl:30
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/ken/.vscode/extensions/julialang.language-julia-0.5.0-beta.3/scripts/languageserver/main.jl, in expression starting on line 41
[Info  - 11:17:54 PM] Connection to server got closed. Server will restart.
```

**Comment by ZacLN** [comment]
`Base.REPLCompletions.completions` is having issues with handing strings containing unicode characters.

It should be an easy fix but I'll have to leave it to tomorrow

**Comment by davidanthoff** [comment]
@ZacLN #97 should fix this. ``Base.REPLCompletions.completions`` is actually fine, but it requires not a character index but a byte index.

**Comment by davidanthoff** [comment]
About the other issue, I think that might be a VS Code limitation right now, see Microsoft/vscode#15841.

@Ken-B, thanks a lot for these two reports. In the future, it would be ideal if you could open separate issues for separate problems, so that we can track them individually.

**Comment by davidanthoff** [comment]
I'm putting this on the backlog for now because the remaining bug is out of our control, afaik.

**Comment by ZacLN** [comment]
\^2 works as a completion on my system (when used from latex_snippets.json). I think we may want to remove the hard coded snippets on the TS side and add a latex_completions.jl  resolver on the server side.

`REPLCompletions` completions returns the full latex label first, then the actual symbol
